### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tanguyantoine** [tanguyantoine/react-native-music-control#1]
# Description

**Android developper needed**

Add behavior to display and control on Android
# Tasks
- [X] Display infos
- [ ] Handle remote control events
- [ ] Display cover artwork from Url/local file

**Comment by cinder92** [comment]
👍

**Comment by Guichaguri** [comment]
@tanguyantoine Is this project still active? I might work on the Android support doing something similar from what I did in [RemoteControls](https://github.com/shi11/RemoteControls/pull/32)

**Comment by tanguyantoine** [comment]
Feel free to do has many PR as you want :)

**Comment by cinder92** [comment]
@Guichaguri  i just have to implement some function in this merge feel free to collaborate :D

**Comment by dininski** [comment]
@cinder92 are you still on this?

**Comment by cinder92** [comment]
@dininski i'm on, but sadly i'm not an android expert, i just edit some functionality, it needs to implement the controls on notification... @Guichaguri are you here to help us?

**Comment by Guichaguri** [comment]
@cinder92 Yes. There are two things that need to be implemented: MediaSession (changes lockscreen background and makes it work with smartwatches and cars), Notification (just a simple notification with media buttons).

For the API, Android supports a lot of options.
Just take a look at the new API implementation I did in [RemoteControls](https://github.com/shi11/RemoteControls/pull/32), it supports most of the options that Android provides.

We should start discussing API changes, if we want to support most of them.

**Comment by cinder92** [comment]
@Guichaguri  yes that true, i saw that this plugin is not working anymore with api 16... this is about media session that is available since API lvl 21, i'm not an android developer but if you need help i can do somenthing...

**Comment by Guichaguri** [comment]
@cinder92 Version compatibility is not a problem when we can use the official support library. The notification works in almost every version and MediaSession can be easily replaced.

Above API 21: MediaSession and Notification
Between API 14-21: RemoteControlClient and Notification
Below API 14: Notification only

For the API, here's all the properties that I was thinking to support:
```js
MusicControl.enableControl('nextTrack', true); // Enabled by default
MusicControl.enableControl('previousTrack', true); // Enabled by default
MusicControl.enableControl('play', true); // Enabled by default
MusicControl.enableControl('pause', true); // Enabled by default
MusicControl.enableControl('stop', false); // Disabled by default
MusicControl.enableControl('seekTo', false); // Disabled by default
MusicControl.enableControl('rate', false); // Disabled by default
MusicControl.enableControl('volume', true); // Enabled by default

MusicControl.setNowPlaying({
  // Track info
  title: 'Prime Time of Your Life', // Required (String)
  artwork: 'http://i.imgur.com/HDDlamS.jpg', // Optional (URL)
  artist: 'Daft Punk', // Required (String)
  album: 'Human After All', // Optional (String)
  description: '', // Optional (String)
  color: 0xd85656, // Optional (Color Number from 0x000000 to 0xFFFFFF)
  genre: 'Industrial Rock, Noise Rock', // Optional (String)
  date: '2006-06-17T00:00:00Z', // Optional (String)
  rating: 77, // Optional (Percentage from 0 to 100)
  duration: 239, // Optional (Number)

  // Playback info
  state: 0, // Required (-1: Error, 0: Stopped, 1: Playing, 2: Paused, 3: Buffering)
  volume: 100, // Optional (Percentage from 0 to 100)
  speed: 1, // Optional (Number. 1: Normal speed)
  elapsedTime: 103, // Optional (Number from 0 to duration)
  bufferedTime: 200 // Optional (Number from 0 to duration)
});

MusicControl.on('play', () => {});
MusicControl.on('pause', () => {});
MusicControl.on('stop', () => {});
MusicControl.on('nextTrack', () => {});
MusicControl.on('previousTrack', () => {});
MusicControl.on('volume', (value) => {}); // Percentage
MusicControl.on('seekTo', (value) => {}); // Position, from 0 to "duration"
MusicControl.on('rate', (value) => {}); // Percentage
```
Obviously most of them will be Android-only since iOS doesn't support them, but that should be documented after we are done.
What you think? Should I change/remove anything?

**Comment by tanguyantoine** [comment]
Awesome

**Comment by Guichaguri** [comment]
@tanguyantoine What is `enableBackgroundMode` supposed to mean? If it's to make the media buttons work in background, what is the point in disabling this?

**Comment by tanguyantoine** [comment]
It is used by iOs if I remember well to allow application to run in background mode with capabilities

**Comment by tanguyantoine** [comment]
@victor36max can I close this one now ?

**Comment by victor36max** [comment]
I think some more changes to be done based on my commit but it basically supports android now

**Comment by Guichaguri** [comment]
There are still lots of problems: The MediaSession still doesn't get any metadata, there is no implemented events for it, it is also not properly released. There are loads of commented and useless code and it is using OS icons. Google recommends not to use them, since they can be changed/removed anytime.

I've been working on a commit to fix all the existing problems, I'll send a PR soon
