### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by DClark5218** [tanguyantoine/react-native-music-control#10]
Can I get a snippet of demo code to implement this?

I've tried to add it, and even though it is not crashing and setting the title music, I find that I cannot successfully fire any events on pause skip, etc.

Please and thank you!

**Comment by tanguyantoine** [comment]
I updated the Readme. But basically register/unregister in `componentDidMount` / `componentWillUnount`

**Comment by DClark5218** [comment]
Thanks!
