### ISSUE TITLE
Headphones unplugged trigger for Android

### ISSUE THREAD

**Issue by jankarres** [tanguyantoine/react-native-music-control#101]
# Description

The package is able to trigger "pause" on headphones unplugged for iOS. This would be a nice feature for Android, too. I this feature should not be complicated to implement think for Android developer in Java. Actually you could help out, @tanguyantoine? Thanks so much for the great work!

Example code: https://twigstechtips.blogspot.de/2013/06/android-detect-when-headsetheadphones.html

Platform
   - [ ] iOS
   - [x] Android
   
Device
  - [ ] Simulator
  - [X] Real device

**Comment by tanguyantoine** [comment]
@Guichaguri any idea ?

**Comment by Guichaguri** [comment]
Yeah, pretty easy to implement, I can work on it when I have time

**Comment by frankros91** [comment]
I don't normally code in Android, but I took a try at this yesterday and it seems to be working.  Might not be the ideal way to do this.  But set up the listener to fire the same PAUSE KeyEvent that is fired when the pause button is pressed in the notification try.
