### ISSUE TITLE
Change Titel in Music Control

### ISSUE THREAD

**Issue by mrsydster** [tanguyantoine/react-native-music-control#102]
I am looking to change the titel in music control. It currently only displays the app name at the top of music control and I want to add the slogan behind it. Is this possible??

**Comment by tanguyantoine** [comment]
which platform ? Can you provide sample code ?

**Comment by mrsydster** [comment]
<img width="413" alt="screen shot 2017-10-21 at 16 30 39" src="https://user-images.githubusercontent.com/21159289/31852741-62f73ef4-b67d-11e7-9017-ffdf91c6151f.png">

I want to change the title highlighted in the screenshot. Can you help me where in the code to do this?

**Comment by Guichaguri** [comment]
@mrsydster That's the name of your app.
