### ISSUE TITLE
[Android] Always show controls MC

### ISSUE THREAD

**Issue by mrsydster** [tanguyantoine/react-native-music-control#103]
How can I make sure that music control will always show the controls on the notifications?

I want to have the same as the app above on the screenshot. Not having to expand the notification.
![screenshot_20171029-165916](https://user-images.githubusercontent.com/21159289/32145538-c9958de8-bcca-11e7-97c0-437059c05b17.png)

**Comment by Guichaguri** [comment]
Duplicate of #67
