### ISSUE TITLE
'React/RCTBridgeModule.h' file not found on iso

### ISSUE THREAD

**Issue by rajeshpanwar007** [tanguyantoine/react-native-music-control#105]
I am using react-native 
react-native-cli: 2.0.1
react-native: 0.49.3

But I am getting following error in MusicControlManager.h file: 

../projects/node_modules/react-native-music-control/ios/MusicControlManager.h:1:9: 'React/RCTBridgeModule.h' file not found

How can I resolve it ?

**Comment by tanguyantoine** [comment]
did you solve it?

**Comment by rajeshpanwar007** [comment]
Hi tanguyantoine,

Yes, I solved it by setting header path.
https://forums.expo.io/t/how-do-i-manually-add-pods-headers-public-to-the-header-search-paths-configuration/2427/6

It worked for me.

**Comment by tanguyantoine** [comment]
any chance you update the README with that?
