### ISSUE TITLE
[ios] Seek to position

### ISSUE THREAD

**Issue by kesha-antonov** [tanguyantoine/react-native-music-control#107]
Hello guys!

Is it possible seek by tapping and moving progress bar of Music Control on iOS?

If it is not implemented yet can you give some advices? I'll provide PR later

Thanks

1. Platform ?
   - [x] iOS
   - [ ] Android
   
@tanguyantoine

**Comment by Ayc0** [comment]
It's not working on my phone either

**Comment by tanguyantoine** [comment]
I'm not sure to understand what you are expecting. Can you elaborate?

**Comment by kesha-antonov** [comment]
On iPhone on lock screen you can tap-and-hold progress bar and move to right/left to desired position in seconds. It's not responding now

@tanguyantoine

**Comment by tanguyantoine** [comment]
Should be fixed. I’ll push a new version soon

**Comment by kesha-antonov** [comment]
Awesome! Thanks! @tanguyantoine

**Comment by tanguyantoine** [comment]
thanks to @DanNi0130
