### ISSUE TITLE
undefined is not an object NativeMusicControl.STATE_PLAYING

### ISSUE THREAD

**Issue by preciousgeorge** [tanguyantoine/react-native-music-control#112]
# Description
   The subject is the error i get. i have updated the code i have still no change.
  react-native-cli: 2.0.1
  react-native: 0.48.4
1. Sample code (provide repo url or sample code)
        
       import MusicControl from 'react-native-music-control'

       export const playCurrentSong = () => {
                       return function (dispatch, getState) {
                        const { songs, currentlyPlaying } = getState()

        let song = null

        if (currentlyPlaying.genre && currentlyPlaying.songIndex >= 0) {
            if (songs[currentlyPlaying.genre.id]) {
                song = songs[currentlyPlaying.genre.id][currentlyPlaying.songIndex]
            }
        }

        MusicControl.enableControl('seekForward', false)
        MusicControl.enableControl('seekBackward', false)
        MusicControl.enableControl('skipForward', false)
        MusicControl.enableControl('skipBackward', false)
        MusicControl.enableBackgroundMode(true)

        MusicControl.on('play', () => dispatch(playCurrentSong()))
        MusicControl.on('pause', () => dispatch(pauseCurrentSong()))
        MusicControl.on('nextTrack', () => dispatch(playNextSong()))
        MusicControl.on('previousTrack', () => dispatch(playPreviousSong()))

        if (song) {
            MusicControl.setNowPlaying({
                title: song.title || "",
                artwork: song.artwork_url || "",
                artist: song.user.username || "",
                genre: song.genre || "",
                duration: song.duration/1000,
                description: song.description || "",
                color: 0xFFFFFFF,
                date: song.created_at,
                rating: true
            })

            MusicControl.updatePlayback({
                state: MusicControl.STATE_PLAYING
                 })
                }

                 dispatch(_updatePaused(false))
               }

           }
                export const pauseCurrentSong = () => {
                             return function (dispatch) {
                                   MusicControl.updatePlayback({
                                       state: MusicControl.STATE_PAUSED
                  })

                  dispatch(_updatePaused(true))
               }

              }
               const _updatePaused = (paused) => ({
                         type: 'UPDATE_PAUSED',
                         paused
              })

2. Platform ?
   - [ ] iOS   
   
3. Device
  - [ ] Simulator

**Comment by pixelvitamina** [comment]
in my project, created via create-react-native-app and ejected to expokit, I had to add the following line to the HEADER_SEARCH_PATHS within the linked MusicControl.xcodeproj 

`$(SRCROOT)/../../../ios/Pods/Headers/Public`

now everything is working

**Comment by tanguyantoine** [comment]
@preciousgeorge could this do the tricks ?

**Comment by AnilkumarDO** [comment]
Any fix for this issue, I am also getting same issue in iOS
