### ISSUE TITLE
support lib v7 update

### ISSUE THREAD

**Issue by Nikhil-Curefit** [tanguyantoine/react-native-music-control#116]
# Description
After updating android support lib to 27.0.2, NotificationCompat becomes deprecated and moved to v4. In v4 the issue is that NotificationCompat.MediaStyle() no longer exists.
The correct fix is to use v4 notification compat and user media style from
import android.support.v4.media.app.NotificationCompat.MediaStyle;

1. Sample code (provide repo url or sample code)
```js
//old code
nb.setStyle(new NotificationCompat.MediaStyle().setMediaSession(session.getSessionToken()));
//new code
nb.setStyle(new MediaStyle().setMediaSession(session.getSessionToken()));
```
2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by deafkittten** [comment]
I've been trying to fix this locally but I have to say that it isn't that easy. MediaStyle is not in the v4 support library. It throws all kinds of errors.

**Comment by Nikhil-Curefit** [comment]
Works fine for me

**Comment by deafkittten** [comment]
Do I need to add any specific support library to the dependencies?

**Comment by Nekith** [comment]
Hello,

I have the same problem.

I tried adding the import, changing the setStyle call, adding "com.android.support:support-v4" dependency in react-native-music-control/android/build.gradle, and I got these errors while running gradle (via "react-native run-android"):

```
:react-native-music-control:processReleaseResources
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
```

I hope it helps somehow.
Thank you.

**Comment by Nikhil-Curefit** [comment]
@deafkittten Just the support lib v4 27.0.2

**Comment by Nikhil-Curefit** [comment]
@Nekith not sure why I didn't face this error. I wrote a simple script if it helps you upgrade. Just run the commands in your project folder

sed -i '' 's/android.support.v7.app.NotificationCompat;/android.support.v4.app.NotificationCompat;import android.support.v4.media.app.NotificationCompat.MediaStyle;/g' node_modules/react-native-music-control/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java
sed -i '' 's/android.support.v7.app.NotificationCompat;/android.support.v4.app.NotificationCompat;/g' node_modules/react-native-music-control/android/src/main/java/com/tanguyantoine/react/MusicControlNotification.java
sed -i '' 's/new NotificationCompat.MediaStyle/new MediaStyle/g' node_modules/react-native-music-control/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java

**Comment by deafkittten** [comment]
Ok, got it to work. Main issue was that I imported the support-library wrong. This one worked for me: `compile "com.android.support:support-v4:27.0.2"`

**Comment by tanguyantoine** [comment]
May I ash you to create a PR to add a Troubleshoot section to the README ? :-)

**Comment by Nekith** [comment]
@Nikhil-Curefit
Thank you, it works.

@tanguyantoine
I could do it but I have to ask: shouldn't we do a PR for the code instead, to update it to be compatible with the Support Lib changes?
