### ISSUE TITLE
setPlaying not working on Android real device but working Android simulator API 25. Please conplain 

### ISSUE THREAD

**Issue by hoangtubatu123** [tanguyantoine/react-native-music-control#122]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [ * ] Android
   
   
3. Device
  - [ ] Simulator
  - [ *] Real device

**Comment by hoangtubatu123** [comment]
playTheSong(index) {
         this.setState({paused: false});
         MusicControl.updatePlayback({
             state: MusicControl.STATE_PLAYING
         });
         MusicControl.setNowPlaying({
             title: this.state.data[index].name,
             artwork: this.state.data[index].image_url, // URL or RN's image require()
             artist: 'Michael Jackson',
             album: 'Thriller',
             genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
             duration: this.state.duration, // (Seconds)
             description: '', // Android Only
             color: 0xFFFFFF, // Notification Color - Android Only
             date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
             rating: 84, // Android Only (Boolean or Number depending on the type)
             notificationIcon: 'my_custom_icon' // Android Only (String), Android Drawable resource name for a custom notification icon
         })
         if (Platform.OS === 'android'){
             MusicControl.enableControl('seek', false) // Android only
         }
         MusicControl.enableControl('play', true)
         MusicControl.enableControl('pause', true)
         MusicControl.enableControl('seekForward', true);
         MusicControl.enableControl('seekBackward', true);
         MusicControl.enableControl('nextTrack', true)
         MusicControl.enableControl('previousTrack', true);
         MusicControl.enableBackgroundMode(true);

     }

**Comment by tanguyantoine** [comment]
can you try with the new version please?

**Comment by hoangtubatu123** [comment]
yeah. let me try

**Comment by arondn2** [comment]
Hi, guys.

I had the same issue and I resolved it adding the permission `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in the AndroidManifest.xml.

Regards.
