### ISSUE TITLE
How to detect the "pause"|"play" button in headphone

### ISSUE THREAD

**Issue by jcliang1212** [tanguyantoine/react-native-music-control#123]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by jcliang1212** [comment]
Ib iOS, we can  detect the "pause"|"play" button in headphone by   MusicControl. on("togglePlayPause",()=>{});
How to use the same function in Android.Can you help me? @tanguyantoine

**Comment by Guichaguri** [comment]
It should work right off the bat with the existing play/pause events.

**Comment by jcliang1212** [comment]
It works! Thank you!!

**Comment by jcliang1212** [comment]
Another question: I just want to use the remote control via headphone in Android, and I do not want the remote control showed in Notification. How to realize this? @Guichaguri  Thank you, very much!

**Comment by Andrfas** [comment]
@jcliang1212 @Guichaguri For some reason not working for me. I'm using the latest version of lib.
Do you know what is required for this to be working?

**Comment by Andrfas** [comment]
On Android, only resuming play is working, but pausing not working. On iOS both pausing and resuming are not working

**Comment by tanguyantoine** [comment]
@Andrfas any source?

**Comment by marf** [comment]
With iOS 11 the `togglePlayPause `is not called when the play/pause button of the headphones is clicked!
