### ISSUE TITLE
How to hide the notification in Android without using resetNowPlaying?

### ISSUE THREAD

**Issue by jcliang1212** [tanguyantoine/react-native-music-control#124]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

I just want to use the remote control via headphone in Android, and I do not want the remote control showed in Notification. How to realize this? @Guichaguri Thank you, very much!

**Comment by tanguyantoine** [comment]
closing (stale)
