### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ayc0** [tanguyantoine/react-native-music-control#128]
Add support for `off` and `stopControl` in README.md

- [ ] off
- [x] stopControl

**Comment by tanguyantoine** [comment]
PR ? :-)

**Comment by Ayc0** [comment]
I've done the one for stopControl, but the other one because I haven't implement it and I don't want to write mistakes

**Comment by tanguyantoine** [comment]
closed by #134

**Comment by Ayc0** [comment]
as the doc for `off` isn't in the readme yet, don't close the issue please

**Comment by tanguyantoine** [comment]
closing due to inativity
