### ISSUE TITLE
Opening the app from MusicControl creates a new intent

### ISSUE THREAD

**Issue by flarocca** [tanguyantoine/react-native-music-control#137]
# Description

When the app is minimized and is opened through the music control, It seems to launch a new intent which cause the app opens as it had been closed, instead of opening the app as it was before going minimized.
What I would like to accomplish is to replicate the default behaviour that Android already has, which when the app is minimized and relaunched from the icon, it opens as it was in the last known state. It produces unexpected behaviours and forces a lot of extra logic

Is there a way to fix this or at least a workaround?

1. Sample code (provide repo url or sample code)

```
class App extends Component {
  componentWillMount() {
    //App initialization
	
    //When opening the app from the icon, this only gets executed once.
    //When opening from MusicControl, this executes each time the app is opened.
  }

  render() {
    return (
      <Navigator />
    );
  }
}
```

How to reproduce?

1- Open the App as usual
2- Call MusicControl.setNowPlaying with the required information while the app is being used.
3- With the MusicControl set, minimize the app
4- Open the app again once from Android directly (meaning from Launch Icon or the task manager) and then compare opening the app from MusicControl.

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

Thanks

**Comment by frenkie** [comment]
@flarocca Yes, this is the same as issue https://github.com/tanguyantoine/react-native-music-control/issues/58, you need to set an 'android:launchMode="..."' in your Android manifest file to make sure the app won't restart. But depending on your needs there are different launchModes to choose from so I suggest reading https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en to choose the right one for you. 'singleTask' worked in my case to fix the problem.

**Comment by machester4** [comment]
You need to `android:launchMode="singleInstance"` in the **activity tag** with the name `.MainActivity` that is in the file `AndroidManifest.xml` **(android / app / src / main / AndroidManifest.xml)**

**Comment by flarocca** [comment]
@frenkie , @machester4 Thanks guys, that really did the trick.
