### ISSUE TITLE
Update to Enable/disable controls README: Necessary to have listener methods inplemented before controls will work

### ISSUE THREAD

**Issue by phil-andrews** [tanguyantoine/react-native-music-control#138]
When I have the methods inside each of these listeners commented out the controls are greyed out on the lockscreen. Of course that's fine, but it's not mentioned in the README that it is a requirement to have controls inside. Would save some debugging time.

1. Sample code (provide repo url or sample code)
```
  MusicControl.on('play', () => {
    // PlayerControls.togglePlayPause()
  })
  MusicControl.on('pause', () => {
    // PlayerControls.togglePlayPause()
  })
  MusicControl.on('togglePlayPause', () => { 
   // PlayerControls.togglePlayPause()
  })
```

Want to make sure that this is the intended behavior before I file a PR. 

2. Platform ?
   - [x] iOS
   - [] Android
  
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
PR ? :-)

**Comment by phil-andrews** [comment]
I mean, if you'd prefer to write it up... :)

**Comment by tanguyantoine** [comment]
The more contributors we have the better the project is
