### ISSUE TITLE
cant pause/resume

### ISSUE THREAD

**Issue by zumaawad** [tanguyantoine/react-native-music-control#14]
# Description

when i pause or resume from app it dosint pause/resume the native

**Comment by tanguyantoine** [comment]
Please provide more details and/or sample code.

**Comment by zumaawad** [comment]
look i made an app streaming mp3 online
and i made a play/pause button
when i play/pause it doesnt change ios music player play/pause button state

**Comment by tanguyantoine** [comment]
Ok

**Comment by zumaawad** [comment]
so how to change it ?

**Comment by tanguyantoine** [comment]
I don't know. If you do not give enough information no one can help you. 
* sample code
* project description
* code which do not work
* iOS or android ?
* all information which can be usefull.

A simple : "it does no work" can't be solved without context and details.

**Comment by deshiknaves** [comment]
I have a very similar issue. RN version 41 IOS.

The play/pause button works as expected. However, the duration keeps going forward even though the music is stopped. I feel like I'm missing something. Is there a way to update the duration time manually?
