### ISSUE TITLE
Error while linking library to iOS Xcode project

### ISSUE THREAD

**Issue by marf** [tanguyantoine/react-native-music-control#140]
Hello, 
I recently added this package to my project and use the command react-native link to link it to Xcode.
The problem is that when I try to compile I get this error:

'React/RCTBridgeModule.h' file not found

I also tried to link manually the library to my project (following the guide in the README) but the problem persists.

I have also tried to remove my node_modules folder and reinstall everything but the problem happens in any way.

I notice that this module is different from the others and it is not installed through cocoa pods, maybe this is the problem?

What should I do?

Best reagards,

Marco

**Comment by tanguyantoine** [comment]
Any chance you share your repository code ? Or reproduce it in a public repo?

**Comment by tanguyantoine** [comment]
Any chance you create a PR from your repo ?

**Comment by tanguyantoine** [comment]
@marf ?

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by tanguyantoine** [comment]
closing (stale)
