### ISSUE TITLE
Error using MusicControls.setNowPlaying()

### ISSUE THREAD

**Issue by geroale** [tanguyantoine/react-native-music-control#141]
Hello,
I have a problem using the function setNowPlaying, that I call when I start the listening of a new song in my app.
The first time I call it everything is fine, but when i set the data again, at the second time, it seems update only the artwork. 

This is the basic form of the call I am using:

```js
MusicControl.setNowPlaying({
        state: MusicControl.STATE_PLAYING,
        title: this.state.trackName,
        artwork: this.state.trackThumbnail.uri,
        artist: this.state.trackArtist,
        album: 'eSound',
        genre: '',
        description: 'eSound',
        color: 0xFFFFFF,
        elapsedTime: 0,
        duration: data.duration,
        date: new Date(),
      })
```

I am calling it when I start a new song within a method and also in a callback of the React Native Video, when the music is loaded (onLoad callback, if you want to check the package api).
Every row in the parameters is correct and anything is null or undefined.
I have tried also calling it more than two times, or using updatePlayback or finally using resetNowPlaying before the call but the glitch seems persist.

I have tested it in iPhone X and some iPhone emulators that runs with iOS 11.
Thanks for reading and sorry for the bad english.
Alessandro.

**Comment by tanguyantoine** [comment]
Any chance you share your repo ?

**Comment by geroale** [comment]
Yes, sure. Can you give me your email or any contact so I can send you the project?

**Comment by arondn2** [comment]
Hi, guys.

I had the same issue and I resolved it adding the permission `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in the AndroidManifest.xml.

Regards.

**Comment by MykolaSauliak** [comment]
> Hello,
> I have a problem using the function setNowPlaying, that I call when I start the listening of a new song in my app.
> The first time I call it everything is fine, but when i set the data again, at the second time, it seems update only the artwork.
> 
> This is the basic form of the call I am using:
> 
> ```js
> MusicControl.setNowPlaying({
>         state: MusicControl.STATE_PLAYING,
>         title: this.state.trackName,
>         artwork: this.state.trackThumbnail.uri,
>         artist: this.state.trackArtist,
>         album: 'eSound',
>         genre: '',
>         description: 'eSound',
>         color: 0xFFFFFF,
>         elapsedTime: 0,
>         duration: data.duration,
>         date: new Date(),
>       })
> ```
> 
> I am calling it when I start a new song within a method and also in a callback of the React Native Video, when the music is loaded (onLoad callback, if you want to check the package api).
> Every row in the parameters is correct and anything is null or undefined.
> I have tried also calling it more than two times, or using updatePlayback or finally using resetNowPlaying before the call but the glitch seems persist.
> 
> I have tested it in iPhone X and some iPhone emulators that runs with iOS 11.
> Thanks for reading and sorry for the bad english.
> Alessandro.

Did you find a solution?
