### ISSUE TITLE
Problem on iOS locked screen, Controls Closed After 2 min

### ISSUE THREAD

**Issue by Salehjarad** [tanguyantoine/react-native-music-control#143]
# Description
* On Locked Screen, after 2 min , the control closed and music stopped.
* On iOS 11, Locked Screen Controls "Play & Pause" button on pressing it , it's turning to gray and not clickable, and the problem is showing "Yellow Box" <= "**RNMusicControlEvent" with no listeners registered.**

![img_0003](https://user-images.githubusercontent.com/17119284/36899717-6d8a222a-1e31-11e8-85be-c917c801d4a2.png)
![img_0004](https://user-images.githubusercontent.com/17119284/36899719-6db30370-1e31-11e8-8724-74d5a06e17b6.png)

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
can you share some code?

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
