### ISSUE TITLE
The metadata is not updated (only the thumb is updated) in iOS 11

### ISSUE THREAD

**Issue by marf** [tanguyantoine/react-native-music-control#144]
# Description
Using the example in iOS the song metadata in the background is not updated, only the thumbnail is updated when I skip and try to listen a new song.

1. Sample code (provide repo url or sample code)
N/A

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by pixelvitamina** [comment]
same here 👍

**Comment by geroale** [comment]
I have the same problem. Not updating the controls on iOS 11.

**Comment by pixelvitamina** [comment]
@tanguyantoine any ideas? easy to fix? thank you!!!

**Comment by tanguyantoine** [comment]
Sorry did not dive into this issue yet. 

Do you have this issue on you own repository or only on the demo one ? May I ask you to give me some information : 

* Did you try another iOS version  ?
* did you follow readme setup instructions ?
* sample code to share ?
* information you think is useful

**Comment by geroale** [comment]
Hi @tanguyantoine , 

We can't try another iOS version by now. We followed carefully the readme and, since it did not work, we have tried to do some fix by ourselves but nothing worked.

Anyway, we can share with you our project to find a fix togheter.
Please contact us on Skype at marco.fontana95 or send us an email at fontana.marco@hotmail.com .

Thank you in advance for the help!

**Comment by smkhalsa** [comment]
@geroale were you able to get this working?

**Comment by geroale** [comment]
Yes, by not using the method updatePlayback to update the song progress (I use it only a few times, to update maybe the status) and by using setNowPlaying really a just one time each song.
Furthermore, be sure to setup everything correctly like controls.

**Comment by timmywil** [comment]
I think this is fixed by b2b1acc293a3a477948176a4a9b7208660827d76

**Comment by tanguyantoine** [comment]
pleas try `0.10.8`?
