### ISSUE TITLE
Lockscreen controls disappear when music is paused

### ISSUE THREAD

**Issue by anker2000** [tanguyantoine/react-native-music-control#147]
On iOS, when I have music running in the background the lock screen controls work as expected, even when I pause and play from the lock screen, however when I pause from within my app and then go to the lock screen the controls are no longer there. How do I make sure it stays even when my music is paused?

**Comment by anker2000** [comment]
Only happened on the simulator - so this questions isn't really relevant.

**Comment by tanguyantoine** [comment]
Is everything working on iOS ? What version are you using ? Which device ?

**Comment by anker2000** [comment]
Yeah pretty much (I'm sometimes get some odd intermittent issues). I'm using the latest version of react-native-music-control and it's running on both iPhone 8 and iPhone X.

**Comment by truckhiem** [comment]
Hi @tanguyantoine any update for this issue. I have same issue and don't know how to fix. Thanks.

**Comment by tanguyantoine** [comment]
@truckhiem can you elaborate and give more information? It does not work on iOS simulator

**Comment by truckhiem** [comment]
@tanguyantoine I tested in iphoneX, it's not work.
I'm using react-native-video to play and react-native-music-control to control music on lockscreen.
- Play video --> control show
- Pause video --> control disappear
I'll share you my code if you need

**Comment by tanguyantoine** [comment]
Please do

**Comment by truckhiem** [comment]
`MusicControl.enableBackgroundMode(true);

        MusicControl.on('nextTrack', () => {
            // MusicControl.resetNowPlaying();
            EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Next});
        });

        MusicControl.on('previousTrack', () => {
            EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Previous});
        });

        MusicControl.on('togglePlayPause', () => {
            // console.warn('togglePlayPause');
            if (this.state.isPauseVideo) {
                EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Play});
            } else {
                EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Pause});
            }
        }); // iOS only
        MusicControl.on('play', () => {
            EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Play});
        });

        MusicControl.on('pause', () => {
            EventBus.getInstance().fireEvent(GlobalString.Event.VideoControl, {code: GlobalString.PlayerControlCode.Pause});
        });

        MusicControl.on('changePlaybackPosition', (pos)=> {
            this.player.seek(pos);
            // EventBus.getInstance().fireEvent(GlobalString.Event.PlayerInfo, {duration: this.state.duration, progress: pos});
        });
        MusicControl.enableControl('setRating', true);
        MusicControl.enableControl('play', true);
        MusicControl.enableControl('pause', true);
        MusicControl.enableControl('nextTrack', true);
        MusicControl.enableControl('previousTrack', true);
        MusicControl.enableControl('closeNotification', true, {when: 'paused'});
        MusicControl.enableControl('togglePlayPause', true);
        MusicControl.enableControl('artwork', true);
        MusicControl.enableControl('changePlaybackPosition', true);
        MusicControl.handleAudioInterruptions(true);`

`EventBus.getInstance().addListener(GlobalString.Event.VideoControl, this.listenerVideoControl = data => {
            if (data.code) {
                switch (data.code) {
                    case GlobalString.PlayerControlCode.Pause:
                        this.setState({
                            isPauseVideo: true,
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.updatePlayback({
                                state: MusicControl.STATE_PAUSED,
                                speed: 0,
                            })
                        }
                        break;
                    case GlobalString.PlayerControlCode.Play:
                        this.setState({
                            isPauseVideo: false,
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.updatePlayback({
                                state: MusicControl.STATE_PLAYING,
                                speed: 0,
                            });
                        }
                        this.isPauseCauseAudioFocusChanged = false;
                        break;
                    case GlobalString.PlayerControlCode.Stop:
                        this.setState({
                            videoUrlBackup: [],
                            videoUrl: ''
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.stopControl();
                            this.isMusicControlSetup = false;
                        }
                        break;
                }
            }
        });`

**Comment by truckhiem** [comment]
`EventBus.getInstance().addListener(GlobalString.Event.VideoControl, this.listenerVideoControl = data => { if (data.code) { switch (data.code) { case GlobalString.PlayerControlCode.Pause: this.setState({ isPauseVideo: true, }); if(this.isMusicControlSetup) { MusicControl.updatePlayback({ state: MusicControl.STATE_PAUSED, speed: 0, }) } break; case GlobalString.PlayerControlCode.Play: this.setState({ isPauseVideo: false, }); if(this.isMusicControlSetup) { MusicControl.updatePlayback({ state: MusicControl.STATE_PLAYING, speed: 0, }); } this.isPauseCauseAudioFocusChanged = false; break; case GlobalString.PlayerControlCode.Stop: this.setState({ videoUrlBackup: [], videoUrl: '' }); if(this.isMusicControlSetup) { MusicControl.stopControl(); this.isMusicControlSetup = false; } break; } } });`

**Comment by truckhiem** [comment]
`EventBus.getInstance().addListener(GlobalString.Event.VideoControl, this.listenerVideoControl = data => {
            if (data.code) {
                switch (data.code) {
                    case GlobalString.PlayerControlCode.Pause:
                        this.setState({
                            isPauseVideo: true,
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.updatePlayback({
                                state: MusicControl.STATE_PAUSED,
                                speed: 0,
                            })
                        }
                        break;
                    case GlobalString.PlayerControlCode.Play:
                        this.setState({
                            isPauseVideo: false,
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.updatePlayback({
                                state: MusicControl.STATE_PLAYING,
                                speed: 0,
                            });
                        }
                        this.isPauseCauseAudioFocusChanged = false;
                        break;
                    case GlobalString.PlayerControlCode.Stop:
                        this.setState({
                            videoUrlBackup: [],
                            videoUrl: ''
                        });
                        if(this.isMusicControlSetup) {
                            MusicControl.stopControl();
                            this.isMusicControlSetup = false;
                        }
                        break;
                }
            }
        });`
