### ISSUE TITLE
Is it possible to follow position of currently playing ?

### ISSUE THREAD

**Issue by ButuzGOL** [tanguyantoine/react-native-music-control#149]
To save last played place

**Comment by Guichaguri** [comment]
This module has nothing to do with the actual position of the current track. It should be the job of your music module to provide you the position from the player.

**Comment by ButuzGOL** [comment]
i am new in this area could you pls share some link with example

**Comment by moonstruck** [comment]
@ButuzGOL Which module you are using to play audio?

**Comment by ButuzGOL** [comment]
I did more digging in apps and understand all !! thanks
