### ISSUE TITLE
Artwork not shown

### ISSUE THREAD

**Issue by XavierColombel** [tanguyantoine/react-native-music-control#15]
I've installed react-native-audio-streaming to play distant files but I don't know how to get your component working together.

Here is my code :
```
render() {
    ReactNativeAudioStreaming.play(this.state.radios.fip.url, {showIniOSMediaCenter: true, showInAndroidNotifications: true});
    MusicControl.setNowPlaying({
      title: 'Test',
      artwork: 'http://lorempixel.com/400/400'
    });
    return (
      <View style={styles.container}>
        <Image
          style={styles.thumb}
          source={require("./assets/radios/fip/400.jpg")}
        />
      </View>
    );
  }
```

- [ ]

**Comment by tanguyantoine** [comment]
Simulator or real device ?

**Comment by XavierColombel** [comment]
Both.

**Comment by tanguyantoine** [comment]
No error ?

**Comment by XavierColombel** [comment]
No error.

**Comment by tanguyantoine** [comment]
Can you create a sample app on github to let me test ?

**Comment by XavierColombel** [comment]
Of course, I'll push it later in the day! ;)

**Comment by XavierColombel** [comment]
Here is my app : [https://github.com/XavierColombel/react-native-radio](url)

**Comment by tanguyantoine** [comment]
Looks to be working

<img width="370" alt="screen shot 2016-11-23 at 22 24 43" src="https://cloud.githubusercontent.com/assets/263097/20579195/b1475560-b1cb-11e6-95cd-798c501f5b73.png">

**Comment by XavierColombel** [comment]
The artwork is not shown.

**Comment by tanguyantoine** [comment]
Can you try with another url than lorempiwel. sometimes their images fail to load.

**Comment by tanguyantoine** [comment]
Eventually with a local file

**Comment by XavierColombel** [comment]
Sorry, I forgot to mention I've tested with other distant files and local files, of course. Did you really get something working on your side?

**Comment by GabeJacobs** [comment]
Also getting this :(

**Comment by tanguyantoine** [comment]
Sorry, I currently have no time to look to this. Are yo able to provide a fix ?

**Comment by XavierColombel** [comment]
Personally I tried but I'm not able. I hope someone will have time to fix this because I really need it! 😊

**Comment by deshiknaves** [comment]
This is probably because you're using a http address. By default iOS will only allow https. And now it's a requirement.

**Comment by tanguyantoine** [comment]
@XavierColombel would you mind trying with a https url ?

**Comment by XavierColombel** [comment]
@tanguyantoine I will try asap and tell you. Did you try it by your side?

**Comment by tanguyantoine** [comment]
nope , I did not

**Comment by deshiknaves** [comment]
I am using it in my app, working exactly as expected. [More about ATS](https://developer.apple.com/news/?id=12212016b)

**Comment by tanguyantoine** [comment]
Can we close ?

**Comment by XavierColombel** [comment]
@tanguyantoine you can close it, I'll reopen it in case @deshiknaves's solution is not working.
