### ISSUE TITLE
Java exception in 'NativeModules' error

### ISSUE THREAD

**Issue by YudizVinay** [tanguyantoine/react-native-music-control#152]
# getting error when run the app
```
E/ReactNativeJS: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: android.support.v7.app.NotificationCompat$Builder
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
```

1. I have just import MusicControl like this in main.js
import { MusicControl } from 'react-native-music-control';

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
   - [ ] Simulator
   - [x] Real device

"react-native": "^0.51.1",
"react-native-music-control": "^0.5.4",

**Comment by tanguyantoine** [comment]
0.7.3 should have fixed it. feel free to ping if it is not the case
