### ISSUE TITLE
Build failure on Android with SDK v27

### ISSUE THREAD

**Issue by jh3141** [tanguyantoine/react-native-music-control#153]
Building per instructions in a project with `compileSdkVersion 27` set gives a large number of unresolved class/package errors during build.  I was able to resolve some of these issues by adding the following line to my `app/build.gradle` file's dependencies section:

```
    compile "com.android.support:support-v4:27.1.1"
```

however this leaves a number of remaining errors relating to classes in the `android.support.v4.media.session` and `android.support.v7.app` packages.  While I have not yet investigated thoroughly, it appears that the notification-related classes in the latter package at least has been deprecated for some time and may have been removed in SDK 27; see https://medium.com/google-developers/migrating-mediastyle-notifications-to-support-android-o-29c7edeca9b7 

(Unfortunately, I cannot downgrade to an older SDK because I'm also using `react-native-camera`, which requires support libs in the v27.x.x range to build)

**Comment by cinder92** [comment]
There are a pull request to update build tools to 26+ please check it

**Comment by tanguyantoine** [comment]
@cinder92 @Guichaguri  is #133  ok ?

**Comment by tanguyantoine** [comment]
solved by #157
