### ISSUE TITLE
Lockscreen controls disappear when music is paused

### ISSUE THREAD

**Issue by lenglengiOS** [tanguyantoine/react-native-music-control#155]
# Description

1. Sample code (provide repo url or sample code)
![image](https://user-images.githubusercontent.com/21171262/40053965-c5411f90-5875-11e8-9364-b7a7b7ebdb13.png)

2. Platform ?
   - [ √] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [√ ] Real device

**Comment by tanguyantoine** [comment]
@lenglengiOS what was the issue ?
