### ISSUE TITLE
NativeMusicControl.STATE_PLAYING ISSUE when testing using EXPO APP

### ISSUE THREAD

**Issue by Shazam14** [tanguyantoine/react-native-music-control#156]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by Shazam14** [comment]
Hi,

I am getting an undefined is not an object (evaluating NativeMusicControl.STATE_PLAYING)
i checked and it doesn't have POD installed, could that be the reason? because as previous recommendation, we should change something inside headers public... could that be the reason?


Thank you,

**Comment by tanguyantoine** [comment]
Did you eject the app? React native music control is not part of expo sdk and that means you cannot use it without ejecting.

**Comment by Shazam14** [comment]
Ok thank you for your response @tanguyantoine apologies for the late response.

**Comment by pedro-lb** [comment]
@Shazam14 did you manage to solve this issue?
