### ISSUE TITLE
Add a callback ?

### ISSUE THREAD

**Issue by XavierColombel** [tanguyantoine/react-native-music-control#16]
It would be interesting to add a callback in order to execute another function after the play function is executed. I think about loading name/artwork song after loading music in player. Today, I use setTimeout.

**Comment by tanguyantoine** [comment]
Any example of you are expecting ? I think this is not the `react-native-music-control` responsability.

**Comment by XavierColombel** [comment]
Sorry, you're right, wrong repo! ;)
