### ISSUE TITLE
Lastest Release Version?

### ISSUE THREAD

**Issue by livelyjp** [tanguyantoine/react-native-music-control#161]
Hi, Been using this package for a while now and just noticed that there are newer releases (0.5.1 >) than what is set as the latest version (v.0.5.0) in the releases tab here on Github https://github.com/tanguyantoine/react-native-music-control/releases. 

Is there any reason why [v.0.7.0](https://github.com/tanguyantoine/react-native-music-control/releases/tag/v0.7.0) is not set with the `latest version` tag and is it a stable enough release?

Assuming its just been missed but just want to check :)

Thanks for all the work on the repo

JP

**Comment by tanguyantoine** [comment]
yep, I was doing it manually. I'm looking for a way to manage it automatically. any recommendations ?

**Comment by renatoalencar** [comment]
I think you could use a Git Hook in order to do that. Maybe a `pre-push` hook, the script would check for the current `latest` tag and the actual latest tag on the repo, and then the script would set the `latest` tag to the current latest tag.

**Comment by renatoalencar** [comment]
This is good

**Comment by tanguyantoine** [comment]
tagged the new version
