### ISSUE TITLE
Android: no control buttons

### ISSUE THREAD

**Issue by kesha-antonov** [tanguyantoine/react-native-music-control#163]
Hello!

I use this lib for ios + android. For ios it works OK. On lock-screen I see control buttons and can press them.
On android I see only bare notification with image and titles. Where should be buttons?

As I remember there were buttons nearly half of year ago. And after OS update they're gone. Does anybody have this problem - no buttons?

Phone: Xiaomi Redmi 4X

![img_8565 copy](https://user-images.githubusercontent.com/11584712/41732112-dd7fdbfc-7588-11e8-9a9f-3eb5f583ce61.jpg)
![img_8564 copy](https://user-images.githubusercontent.com/11584712/41732113-dda43dd0-7588-11e8-9c0e-5377a6989dc7.jpg)

2. Platform ?
   - [ ] iOS
   - [x ] Android
   
   
3. Device
  - [ ] Simulator
  - [x ] Real device

**Comment by jamsch** [comment]
On my Xiaomi Mi Max 2, react-native-music-control only displays controls when the notification is expanded.

It probably needs a redesign because other apps don't do this.

**Comment by The0racle** [comment]
Same thing happening to me. Nexus 5X, Android version: 6.0.

**Comment by marioot** [comment]
Same thing happens Samsung Galaxy S5, Android version: 6.0

**Comment by Adam3306** [comment]
anybody?

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by tanguyantoine** [comment]
closing (stale)
