### ISSUE TITLE
Android build: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat

### ISSUE THREAD

**Issue by andtos90** [tanguyantoine/react-native-music-control#165]
After the last release (v0.7.3) I found this error while compiling my Android application:

`com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat`

I think that the problem is caused by this line inside the library build.gradle: 
`compile 'com.android.support:support-media-compat:26.+`

To be able to solve the problem I simply added this code to my application build.gradle (app folder):

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.1'
            }
        }
    }
}
```

Has anyone a better solution that doesn't need a special configuration for this library?

**Comment by tanguyantoine** [comment]
Any chance you provide a PR for that ?

**Comment by andtos90** [comment]
I can only send a PR to edit the README because the new gradle configuration should be used inside the RN final application. I'm still looking for a better solution to avoid a configuration specific to this library

**Comment by tanguyantoine** [comment]
That's a better than nothing :-)
