### ISSUE TITLE
Undefined is not an object (NativeMusicControl.STATE_PLAYING)

### ISSUE THREAD

**Issue by ramos-lucas** [tanguyantoine/react-native-music-control#167]
![image](https://user-images.githubusercontent.com/18932708/42069136-6f253f82-7b26-11e8-8375-46621d1ef9e9.png)

I've created a new project just to test this package along with 'react-native-sound'.
This is just an example "copy and paste", but only with (`import MusicControl from 'react-native-music-control';`), the error already occurs.

What is wrong?

1. Sample code (provide repo url or sample code)
``` javascript
const sound = new Sound(
"https://www.sample-videos.com/audio/mp3/crowd-cheering.mp3",
      null,
      error => {
        if (error) {
          Alert.alert(error);
        }
        sound.play();
        MusicControl.setNowPlaying({
          title: 'Billie Jean',
          artwork: 'https://i.imgur.com/e1cpwdo.png', // URL or RN's image require()
          artist: 'Michael Jackson',
          album: 'Thriller',
          genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
          duration: 294, // (Seconds)
          description: '', // Android Only
          color: 0xFFFFFF, // Notification Color - Android Only
          date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
          rating: 84, // Android Only (Boolean or Number depending on the type)
          notificationIcon: 'my_custom_icon' // Android Only (String), Android Drawable resource name for a custom notification icon
        });
      }
    );
```

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [ ] Real device

**Comment by Guichaguri** [comment]
This issue usually comes up when you don't link the module properly

**Comment by ramos-lucas** [comment]
I've linked using `react-native link` and confirmed using the manual steps.

**Comment by ramos-lucas** [comment]
I've tried again:
- `yarn add react-native-music-control && yarn add react-native-sound`
- `react-native link`
- `react-native run-android`

The result was:
![image](https://user-images.githubusercontent.com/18932708/42128982-ee492f7c-7c8d-11e8-9504-2f73c1976b7f.png)

**Comment by ramos-lucas** [comment]
Someone can help me? Is the last thing to finish my project.
In `constants.android.js` there isn't a property called MusicControlManager on imported object NativeModules.

I'm using react-native v0.55.4 and react-native-music-control v0.7.3

**Comment by ramos-lucas** [comment]
I had to install the version ^0.4.13 that I already had tested.

**Comment by tanguyantoine** [comment]
using 0.4.13 fixed the issue?

**Comment by ramos-lucas** [comment]
Yes, using 0.4.3 is working fine.

**Comment by webfalcon** [comment]
Still getting this issue starting 0.4.0 version. 

Is there anyone who solved the problem?

**Comment by tanguyantoine** [comment]
please try with 0.4.13

**Comment by webfalcon** [comment]
0.4.13 also has same issue

**Comment by moonstruck** [comment]
@webfalcon have you linked the library?
`react-native link react-native-music-control`

**Comment by webfalcon** [comment]
Yes!I also tried manual linking. But it's looks like not linked.

**Comment by moonstruck** [comment]
I'm using this library for almost a year. No major issues so far.
Share `react-native info` output.

You may try a clean installation first.

**Comment by obzc** [comment]
`pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'`
after run `pod install`

**Comment by tanguyantoine** [comment]
@obzc could you update the README?

**Comment by tanguyantoine** [comment]
di you run pod install ?

**Comment by gazedash** [comment]
Can reproduce this. Installed this library, linked, installed pods. Version 0.9.8

**Comment by pedro-lb** [comment]
I'm also having this issue.

Details here: https://github.com/tanguyantoine/react-native-music-control/issues/303

@ramos-lucas did you manage to solve the issue?

**Comment by ramos-lucas** [comment]
@pedro-lb I changed to v0.7.3

**Comment by pedro-lb** [comment]
Thanks @ramos-lucas! Unfortunately this didn't solve the issue. Looking forward for Expo 36.

**Comment by tanguyantoine** [comment]
expo issue: https://github.com/software-mansion/react-native-gesture-handler/issues/676
