### ISSUE TITLE
not working on iOS

### ISSUE THREAD

**Issue by dominicsavb** [tanguyantoine/react-native-music-control#168]
I didn't see anything show at my iOS simulator or iOS real device? but works well at android.

I use iOS 11.4 and xcode 9.4.1

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [X] Simulator
  - [X] Real device

**Comment by tanguyantoine** [comment]
Would you mind giving more detail

**Comment by holospeed** [comment]
I faced with the same issue.

**OS**: macOS High Sierra (10.13.5)

**Xcode** : Version 9.4.1 (9F2000)
**iOS Deployment Target**: 9.0
**Capabilities**: Background Modes/ Audio, AirPlay, and Picture in Picture

**device**: iPhone 6s (Real device)
**device OS Version**: 11.4

**react-native**: 0.56.0
**yarn**: 1.5.1

**Steps**:
* react-native init myProject
* cd myProject
* yarn add react-native-music-control 
 * react-native link react-native-music-control 
* cd ios
* open myProject.xcodeproj
* checked background mode at Capabilities (Audio, AirPlay, and Picture in Picture)
* Build and run on iPhone 6s.


**Project Details**:
  _Sample React Native App:_

```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import MusicControl from 'react-native-music-control';


type Props = {};
export default class App extends Component<Props> {

  render() {

    MusicControl.setNowPlaying({
      title: 'Billie Jean',
      artwork: 'https://i.imgur.com/e1cpwdo.png', // URL or RN's image require()
      artist: 'Michael Jackson',
      album: 'Thriller',
      genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
      duration: 294, // (Seconds)
      description: '', // Android Only
      color: 0xFFFFFF, // Notification Color - Android Only
      date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
      rating: 84, // Android Only (Boolean or Number depending on the type)
      notificationIcon: 'my_custom_icon' // Android Only (String), Android Drawable resource name for a custom notification icon
    })

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
          <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}></Text>
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

**Comment by tanguyantoine** [comment]
https://github.com/tanguyantoine/react-native-music-control#enabledisable-controls have you enable controls ?

**Comment by holospeed** [comment]
Okay! 😁
It was not clear to me from the documentation that I have to play sound / music if I want to test/use the music control. Whitout music the media control won't show up. The issue was in my head not in the code...  sorry 😊

**Comment by ThadeusAjayi** [comment]
> I didn't see anything show at my iOS simulator or iOS real device? but works well at android.
> 
> I use iOS 11.4 and xcode 9.4.1
> 
> 1. Sample code (provide repo url or sample code)
> 2. Platform ?
>    
>    * [x]  iOS
>    * [ ]  Android
> 3. Device
> 
> * [x]  Simulator
> * [x]  Real device

On iOS if MusicControl.enableControl('pause', true) while playing, notification would not show

**Comment by shaheer904** [comment]
Nothing is working on IOS.
