### ISSUE TITLE
React native compatibility version

### ISSUE THREAD

**Issue by cinder92** [tanguyantoine/react-native-music-control#17]
that the question, is not compatible with RN >= 0.38

**Comment by tanguyantoine** [comment]
PR ?

**Comment by cinder92** [comment]
i'm trying to set local in artwork, but it seems that even when i'm passing absolute url and returning a bitmap is not recognizing image, even from url is not showing....

**Comment by tanguyantoine** [comment]
Can you elaborate
* sample code
* platform
* real device ?

**Comment by tanguyantoine** [comment]
Please create a new issue. I updated the template
