### ISSUE TITLE
Controls not shown after displaying video (iOS)

### ISSUE THREAD

**Issue by danielmcmillan** [tanguyantoine/react-native-music-control#171]
After presenting AVPlayerViewController (with react-native-video), then dismissing the controller, now playing info set by react-native-music-control is no longer displayed.

AVPlayerViewController sets the now playing info itself while playing, and clears it when dismissed.
Terminating and relaunching the app is required to get the controls set by this library to display again.

1. Sample code

[Simple react-native app](https://gist.github.com/danielmcmillan/a27498d1703459cbbf0144fb4d99854f) using react-native-video to present full-screen AVPlayerViewController.
Using react-native-music-control version 0.7.3, react-native-video 2.3.1.

2. Platform ?
   - [x] iOS 11.4
   - [ ] Android

3. Device
  - [x] Real device

**Comment by hellogerard** [comment]
@danielmcmillan You would have to call `setNowPlaying` or otherwise re-initialize everything again after the video. Does that not work?

**Comment by danielmcmillan** [comment]
@hellogerard No it doesn't seem to. You can see the function attempting to initialise the controls in the linked Gist.The only way I was able to get the controls to display again is by killing and relaunching the app (reloading JavaScript has no effect).

**Comment by holospeed** [comment]
Hi! Same issue :/  Is there any workaround ?

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by tanguyantoine** [comment]
closing (stale)
