### ISSUE TITLE
Is there some event when pressing the notification?

### ISSUE THREAD

**Issue by ramos-lucas** [tanguyantoine/react-native-music-control#173]
# Description
Is there some event to prevent my component to be remounted?

I'm using `react-native-sound` and when I press the notification my component is remounted, playing a new song and I don't have the sound instance anymore.

I'm beginning with react native, how i should proceed?

1. Sample code (provide repo url or sample code)

2. Platform
   - [ ] iOS
   - [x] Android
   
   
3. Device
   - [x] Simulator
   - [ ] Real device

**Comment by tanguyantoine** [comment]
Could you share some code?

**Comment by ramos-lucas** [comment]
I've created an issue on `react-native-sound` too to find a better solution to manage sound instances, but for now my only problem is when pressing the notification.

``` javascript
componentDidMount() {
    this.newMusic();
    MusicControl.enableControl('closeNotification', true, {
        when: 'always',
    });
    MusicControl.enableControl('stop', true);
    MusicControl.on('play', () => {
        this.onPlay();
    });
    MusicControl.on('stop', () => {
        this.onStop();
    });
}


newMusic = (id = 0) => {
    const { playlist, trackPlayed } = this.state;
    const sound = new Sound(playlist[trackPlayed], null, error => {
        if (error) {
            sound.reset();
        } else {
            this.setState({ sound }, () => {
                this.onPlay();
            });
        }
    });
};

onPlay = () => {
    const { sound, trackPlayed, playlist } = this.state;
    MusicControl.setNowPlaying({
        artwork: logo80,
    });
    MusicControl.enableControl('stop', true);
    sound.play(success => {
        if (success) {
            sound.release();
            this.setState({
                    trackPlayed: trackPlayed < playlist.length - 1 ? trackPlayed + 1 : 0,
                },
                () => {
                    this.newMusic(this.state.trackPlayed);
                },
            );
        }
    });
    this.setState({
        isPlaying: true
    });
};

onStop = () => {
    const { sound } = this.state;
    MusicControl.resetNowPlaying();
    sound.stop();
    this.setState({ isPlaying: false });
};
```

**Comment by tanguyantoine** [comment]
Sorry, I'm not sure to understand correctly what you try to achieve. What you wrote looks good. Which notification are you talking about?

**Comment by ramos-lucas** [comment]
The notification card in the notification bar (not the buttons play/stop). When I press it my app is remounted, starting a new sound because of `ComponentDidMount`.

**Comment by ramos-lucas** [comment]
@moonstruck That's it! Thanks
