### ISSUE TITLE
iOS 11 - togglePlayPause event is not called when the play/pause button of the headphones is clicked

### ISSUE THREAD

**Issue by marf** [tanguyantoine/react-native-music-control#174]
# Description

With iOS 11 the `togglePlayPause ` event is not called when the play/pause button of the headphones is clicked!
You can check it in a blank project by simply printing a `console.log()` like this:

```
    MusicControl.on('togglePlayPause', () => {
      console.log('switch play/pause');
    });
```

The console.log() is never called when clicking the physical button of the headphones.

1. Sample code (provide repo url or sample code)
none

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by geroale** [comment]
Same problem here. Tried everything...

**Comment by marf** [comment]
Any news?

**Comment by tanguyantoine** [comment]
Sorry, I did not had time to dig into this issue. Do you have some iOS knowledges?

**Comment by marf** [comment]
I have searched something but without the correct documentation of the code I cannot know how to proceed

**Comment by hellogerard** [comment]
It works for me. Maybe you have to enable it?

```js
    MusicControl.enableControl('togglePlayPause', true);
    MusicControl.on('togglePlayPause', () => (
      // ...
    ));
```

**Comment by kesha-antonov** [comment]
@hellogerard yeah. We should run ```MusicControl.enableControl('togglePlayPause', true)```
thanks

**Comment by kesha-antonov** [comment]
@tanguyantoine I think this can be closed
