### ISSUE TITLE
Can't build on android target sdk 27

### ISSUE THREAD

**Issue by appaaaa** [tanguyantoine/react-native-music-control#176]
I have a problem.. anyone has problem?

target sdk 27
classpath 'com.android.tools.build:gradle:3.1.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

![1](https://user-images.githubusercontent.com/26356032/43117879-19817e6e-8f4a-11e8-92b6-94f32df8cae4.PNG)

**Comment by appaaaa** [comment]
./gradlew clean has same problem

**Comment by Guichaguri** [comment]
It's a conflict between your target SDK and the support lib.
The support lib has to match the same version as the target SDK

**Comment by appaaaa** [comment]
`dependencies {
    compile project(':react-native-sound')
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile project(':react-native-music-control')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:+"
    compile "com.facebook.react:react-native:+"  // From node_modules
}`

I'm using this and build well.
It's problem only using 'react-native-music-control'...

**Comment by appaaaa** [comment]
I solve build errors

appcompat-v7:+ -> appcompat-v7:27.0.1 // explicit version

and add
maven { url 'https://maven.google.com' } // over the jcenter() in 'android/build.gradle'

and react-native link doesn't add compile project(':react-native-music-control') to app/build.gradle
so add it manually.

**Comment by tanguyantoine** [comment]
@appaaaa any chance you create a PR to update the README accordingly? 🙏

**Comment by Guichaguri** [comment]
@tanguyantioine It's not a common react-native-music-control issue nor it's a react-native issue, it's actually a common Android issue. I don't see a reason to add it to our README since it only happens to who changes a specific library in their `build.gradle`, most of the people using this module never mess around with their Android setup anyway. There is also plenty of StackOverflow questions about it.
