### ISSUE TITLE
Error: MusicControl is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by seque1990** [tanguyantoine/react-native-music-control#178]
# Description

I wanted to install react-native-music-control into my project and stumbled onto the following issues

```
MusicControl.java:13: error: MusicControl is not abstract and does not override abstract method createJSModules() in ReactPackage
public class MusicControl implements ReactPackage {
       ^

MusicControlModule.java:134: error: constructor Builder in class Builder cannot be applied to given types;
        nb = new NotificationCompat.Builder(context, CHANNEL_ID);
             ^
  required: Context
  found: ReactApplicationContext,String
  reason: actual and formal argument lists differ in length
```

Here my app/builde.gradle sdk settings:

compileSdkVersion : 26
buildToolsVersion : 26.0.1
minSdkVersion 16
targetSdkVersion 26

2. Platform ?
   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [ ] Simulator
  - [X] Real device

**Comment by tanguyantoine** [comment]
did you solved the issue?

**Comment by yasheshkt** [comment]
@seque1990 - Thats really good work you did for compatibility in RN 0.44. Thanks for the work mate. I just had a question, the Android Oreo Problem is solved as off your last commit "Try placing stop first" commit?

**Comment by tanguyantoine** [comment]
any chance you create a PR here with your changes?

**Comment by seque1990** [comment]
@tanguyantoine  Sorry, I completely forgot about this. Is this still needed?

**Comment by tanguyantoine** [comment]
No clues ^^
