### ISSUE TITLE
crashed app on ios 8.x

### ISSUE THREAD

**Issue by QuietListener** [tanguyantoine/react-native-music-control#181]
# Description
2018-08-14 17:44:15.422 ireading_rn[93273:2062647] -[MPRemoteCommandCenter enableLanguageOptionCommand]: unrecognized selector sent to instance 0x7fccb5b67760
2018-08-14 17:44:16.448 ireading_rn[93273:2062445] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MPRemoteCommandCenter enableLanguageOptionCommand]: unrecognized selector sent to instance 0x7fccb5b67760'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102e20a75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103ac3bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000102e27d1d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000102d7f9dc ___forwarding___ + 988
	4   CoreFoundation                      0x0000000102d7f578 _CF_forwarding_prep_0 + 120
	5   ireading_rn                         0x00000001024516ba -[MusicControlManager stop] + 538
	6   ireading_rn                         0x000000010245140b -[MusicControlManager dealloc] + 43
	7   libobjc.A.dylib                     0x0000000103ad828e _ZN11objc_object17sidetable_releaseEb + 236
	8   libobjc.A.dylib                     0x0000000103ad88cd _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 591
	9   CoreFoundation                      0x0000000102d17706 _CFAutoreleasePoolPop + 22
	10  Foundation                          0x0000000103679862 __NSThreadPerformPerform + 491
	11  CoreFoundation                      0x0000000102d55c91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	12  CoreFoundation                      0x0000000102d4bb5d __CFRunLoopDoSources0 + 269
	13  CoreFoundation                      0x0000000102d4b194 __CFRunLoopRun + 868
	14  CoreFoundation                      0x0000000102d4abc6 CFRunLoopRunSpecific + 470
	15  ireading_rn                         0x0000000101fa385b +[RCTCxxBridge runRunLoop] + 1035
	16  Foundation                          0x000000010367c1dd __NSThread__main__ + 1194
	17  libsystem_pthread.dylib             0x000000010819f661 _pthread_body + 340
	18  libsystem_pthread.dylib             0x000000010819f50d _pthread_body + 0
	19  libsystem_pthread.dylib             0x000000010819ebf9 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS

   
   
3. Device
  - [ ] Simulator
  - [ ] Real device

**Comment by tanguyantoine** [comment]
You are right, this package does not deal with older version of iOS
