### ISSUE TITLE
Controls doesn't work when I minimize/close app

### ISSUE THREAD

**Issue by ithustle** [tanguyantoine/react-native-music-control#182]
# Description

I followed the documentation and react-native-youtube-player implementation as example and when I minimize or close my app, controls on notification doesn't work.

2. Platform ?
   - [ ] iOS
   - [X ] Android
   
   
3. Device
  - [ ] Simulator
  - [X ] Real device

RN version: 0.56.0

**Comment by tanguyantoine** [comment]
closing (stale)
