### ISSUE TITLE
clicking notification banner re-opens app and re-starts stream (Android)

### ISSUE THREAD

**Issue by taliseen** [tanguyantoine/react-native-music-control#183]
# Description
While playing an audio stream, When I click the notification banner on a Galaxy S8 Plus it doesnt just go to the open app, it re-opens the app, showing the splash screen again and proceeds to restart the stream, over top the existing stream.

This continues to happen indefeinitely, like the amount of times I click the notification is the amount of concurrent, conflicting streams.   We are using react-native-video to connect to the stream. 

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by moonstruck** [comment]
@taliseen use `android:launchMode="singleTop"` in AndroidManifest.

**Comment by taliseen** [comment]
I have that twice in AndroidManifest.xml (see below) . Any ideas?

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.kvan3">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

        <activity
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:launchMode="singleTop"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

      <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

**Comment by danielmcmillan** [comment]
@taliseen Using `android:launchMode="singleTask"` for MainActivity fixed the issue for me.

I guess MainActivity is not at the top when the notification is opened since it starts the launch intent (which launches SplashActivity), so a new MainActivity is created even with "singleTop" launch mode.

**Comment by taliseen** [comment]
Ahh thanks @danielmcmillan this worked perfectly!  i replaced singleTop the two places it was and we are in business!

**Comment by taliseen** [comment]
Sure sorry for the dumb question but do I need to create a new branch and then push to that tracking branch to do a pull request?

What are the exact steps to do a proper pull request?

**Comment by tanguyantoine** [comment]
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ I can't explain it in a better way :-)

**Comment by taliseen** [comment]
Thanks for the help
