### ISSUE TITLE
ios audio stream starts unexpectedly upon recieving text message, music controls dont always reflect state of app, and restart shoutcast stream with no user input at times

### ISSUE THREAD

**Issue by taliseen** [tanguyantoine/react-native-music-control#184]
# Description
When streaming audio using https://github.com/react-native-community/react-native-video from a shoutcast audio stream endpoint, and then hitting pause, sometimes the stream comes on unexpectedly upon recieving a text message.  This can be startling as the user does not want the stream to start at that time.

Is there anything specific that we need to do to handle audio streams as opposed to discrete audio files in terms of handling the music controls state?  Why would a text message trigger the stream to come back on without the user hitting play?  

Could it be that it isn't properly connected to the state of the app itself in the background?

Thanks,
TaliSeen

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by a-koka** [comment]
This is happening to me daily on iOS. In my case, it doesn't have to do with text message trigger as it happens randomly. I'm also using react-native-sound to play local files, not streaming.

When this happens, the app is not running and the music **randomly** starts playing. When I start the app, it gets stuck on a white screen. Only upon killing the app, does the sound go away.

I've tried completely unliking `react-native-music-control` and the problem still happens.

**Comment by tanguyantoine** [comment]
What make you think it relatest to this library rather than reac native sound?

**Comment by a-koka** [comment]
It started happening only after adding this library to my app which has been live for 3 years and I've been using `react-native-sound` since the beginning without any issues. I only need music-control on Android so after disabling this library on iOS using `react-native.config.js` so that the library is not bundled on iOS, the problem goes away.

**Comment by luqmanrom** [comment]
This happened to me on Google Pixel at least. It will randomly start playing the sound after certain actions ie viewing Insta story, Whatsapp video call. Not exactly sure the culprit is this library of react-native-video
