### ISSUE TITLE
android audio stream plays through phone call

### ISSUE THREAD

**Issue by taliseen** [tanguyantoine/react-native-music-control#185]
# Description
Is there a way to make the stream stop during a phone call and restart again afterwards, as in ios?

Perhaps this is an issue with https://github.com/react-native-community/react-native-video and not this library?

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [ ] Real device

**Comment by tanguyantoine** [comment]
You are correct, this has nothin to do with this library. sorry
