### ISSUE TITLE
Pause doesn't work on Android

### ISSUE THREAD

**Issue by ArtemKosiakevych** [tanguyantoine/react-native-music-control#187]
# Description

Headphone pause/stop button doesn't trigger any action

1. Sample code (provide repo url or sample code)
```
    MusicControl.enableControl('play', true)
    MusicControl.enableControl('pause', true)
    MusicControl.on('pause', this.onPlay)
    MusicControl.on('play', this.onPlay)
```

`this.onPlay` didn't call 

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
Any chance you share your code?

**Comment by john-hu** [comment]
I got a similar issue. The pause at notification bar works. But the media button which triggers pause doesn't work.

I am working on an open source project, you may find it at https://github.com/Vosie/QianLiYan. I am using version 0.5.0. The issue also happens to my experiment branch for upgrading to RN 0.57, https://github.com/Vosie/QianLiYan/tree/rn0-57.

**Comment by tanguyantoine** [comment]
Can you try upgrading to the latest version, 0.9.5 ?

**Comment by PromitRai** [comment]
i have same issue. Pause button doesn't show up. I did update to 0.9.5 but still have same issue.

**Comment by john-hu** [comment]
@tanguyantoine I had tested the 0.9.5. It doesn't work. I found the following things:

- The `closeNotification` doesn't work at both `0.9.5` or `0.7.3` versions.
- The `pause` through headset doesn't work at both `0.9.5` or `0.7.3` versions.
- The `lock screen` music control doesn't show up at both `0.9.5` or `0.7.3` versions.

But it works correctly at the old version, IIRC.

**Comment by john-hu** [comment]
Ok. good news. I found the music control at lock screen works at my Android 9 device.

**Comment by Adam3306** [comment]
up!

**Comment by tanguyantoine** [comment]
@Adam3306 what is your issue? 
@john-hu What did you do to fix it?

**Comment by iamraffe** [comment]
I having this issue. Is there a fix / patch I could try?

**Comment by Adam3306** [comment]
Hi!

I cant solve the problem :(

Adam

raffe <notifications@github.com> (időpont: 2019. jún. 11., K, 13:21) ezt
írta:

**Comment by john-hu** [comment]
@tanguyantoine Sorry for late replying. I got a lot of works recently. I didn't fix it. I just install the app to my new device which is Android 9. The issue is still there.

**Comment by gazedash** [comment]
Pause and other buttons doesn't work on lock screen on Samsung, Android 9

**Comment by iamraffe** [comment]
This fixed it for me -> https://github.com/tanguyantoine/react-native-music-control/issues/42#issuecomment-298464494

It seems we just need to be as explicit as possible.

Got this working in a Samsung S10+!
