### ISSUE TITLE
Music Controls do not update when app is in background.  

### ISSUE THREAD

**Issue by taliseen** [tanguyantoine/react-native-music-control#188]
# Description
We are connecting to a shoutcast stream for a radio station stream.  When the song changes the music controls dont change the metadata until i reopen the app, even though its playing in the background. 

Do I need to use something like this?  https://github.com/jamesisaac/react-native-background-task

Unfortunately it would only allow updating every 15 minutes on android. 

Is there any way to force music controls to keep polling the app for changes?  

It seems the updateMusicControls method does not run in the background...

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [x] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
solved?

**Comment by bradleyflood** [comment]
Hi @taliseen are you referring to Android only? I can confirm that these lock screen controls DO work correctly for me on iOS when app is in background mode. My app plays a queue of songs so this is essential functionality that I have tested.
I have not tested Android yet however. Do you mean just Android?

**Comment by Guichaguri** [comment]
It's an issue due to this library not being tied to the directly to the player running in background. To solve the issue, I created [react-native-track-player](https://github.com/react-native-kit/react-native-track-player), a module that runs the music controls in the same service as the player.

**Comment by Guichaguri** [comment]
It might be possible to try a workaround, but it'll probably be very buggy and unstable. Running the player with music controls side-by-side is the easier and proper solution.

**Comment by tanguyantoine** [comment]
> Ha, maybe this should not be in the thread but it may help others running into this same bug

Definitely ^^. You should move this discussion to the `react-native-track-player`'s repository
