### ISSUE TITLE
Overlap title and artist name on iOS lock screen

### ISSUE THREAD

**Issue by Tejas-narola** [tanguyantoine/react-native-music-control#189]
React-native verison: 0.54.0
react-native-music-control@0.5.5
https://trello-attachments.s3.amazonaws.com/5b5f0e42b99a6bbb70ae3bc4/5babf34a4bf09d44d4f346a5/22414a4f6d1fd52a1d8467b543fafb40/image.png

2. Platform ?
   - [x] iOS
   
3. Device
   - [x] Real device

**Comment by tanguyantoine** [comment]
I don't thin this issue is related to this package. 
What iOs version are you running? 
Does this issue still appear with the last package version?
