### ISSUE TITLE
Possible to show live indicator instead of progress scrubber?

### ISSUE THREAD

**Issue by hellogerard** [tanguyantoine/react-native-music-control#190]
### Description

1. Hi! This package works great.  I noticed the below in my radio app. Note the `((( LIVE )))` indicator.
    

    <img width="400" src="https://user-images.githubusercontent.com/200488/47857284-9dc18e80-ddbf-11e8-98b0-43f2bdc60382.PNG">

    
    For controlling a livestream (e.g. `m3u8`), is it possible to show the live indicator instead of the progress bar / scrubber? If not, this could be a good enhancement.

2. Platform: I'm only concerned with iOS. I don't know if this is a thing on Android.
   - [x] iOS
   - [ ] Android

3. Device:
    - [ ] Simulator
    - [x] Real device

**Comment by tanguyantoine** [comment]
That sounds like a perfect enhancement. ANy doc we can refer to? Is it something you can implement?

**Comment by ahmetsozkesen** [comment]
I know it's been a while but in PR #347 this issues has been solved.

**Comment by bradleyflood** [comment]
Deploying in `1.0.1` thanks @ahmetsozkesen
