### ISSUE TITLE
Controls hide on lock screen (Android)

### ISSUE THREAD

**Issue by ithustle** [tanguyantoine/react-native-music-control#192]
Hi 
Its not a issue but do you have an intention to update it to show music controls on lock screen if I set notification hide on screen?

I think will be a good asset on your good work. 

Cheers 

Célio Garcia

2. Platform ?
   - [ ] iOS
   - [X ] Android
   
   
3. Device
  - [ ] Simulator
  - [X ] Real device

**Comment by tanguyantoine** [comment]
If you have any skills and want to contribute, this is something we definitely can merge.

**Comment by tanguyantoine** [comment]
You rock 👍

**Comment by PromitRai** [comment]
did anyone manage to solve this ?

**Comment by tanguyantoine** [comment]
@ithustle we are waiting your PR :-P

**Comment by tanguyantoine** [comment]
haha good luck ^^

**Comment by ithustle** [comment]
hehehe great incentive

**Comment by tanguyantoine** [comment]
sorry, I'm not an android expert ... at all

**Comment by Adam3306** [comment]
pls guys help

**Comment by ithustle** [comment]
@lufinkey , I think you saved my ass 😆

**Comment by lufinkey** [comment]
This issue should be re-opened since that PR crashed in some instances. I think I know a better way to implement it that doesn't hardcode the actions. I'll take another crack at it sometime this week

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
