### ISSUE TITLE
Demo Application

### ISSUE THREAD

**Issue by tanguyantoine** [tanguyantoine/react-native-music-control#2]
# Description

It will be a great idea to create a complete example (application)
# Tasks
- [x] iOS app
- [ ] Android app
- [x] Use control
- [x] Play music
- [x] Enable/disable
- [x] Display info

**Comment by zumaawad** [comment]
I will post a demo app as soon as possible

**Comment by tanguyantoine** [comment]
https://github.com/tanguyantoine/react-native-music-control-demo

@Guichaguri can you update with android code ?

**Comment by Guichaguri** [comment]
Once the iOS version supports `setPlayback`, we can finally unify the code for iOS and Android.
We could add a proper UI, and maybe use the Soundcloud API for playback and metadata. What do you think?

**Comment by jasongrishkoff** [comment]
As an alternative to SoundCloud API, I've been using this library for playback -- has been quite smooth: https://github.com/indiecastfm/react-native-audio-streamer

**Comment by tanguyantoine** [comment]
demo link : https://github.com/tanguyantoine/react-native-music-control-demo

would be great if someone can push the part for Android
