### ISSUE TITLE
package android.support.v4.media.app.NotificationCompat does not exist

### ISSUE THREAD

**Issue by mojtaba-hajishah** [tanguyantoine/react-native-music-control#200]
1. Description
I get this error when I run react-native run-android:

...\node_modules\react-native-music-control\android\src\main\java\com\tanguyantoine\react\MusicControlModule.java:27: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;

...\node_modules\react-native-music-control\android\src\main\java\com\tanguyantoine\react\MusicControlModule.java:142: error: cannot find symbol

        nb.setStyle(new MediaStyle().setMediaSession(session.getSessionToken()));

symbol:   class MediaStyle
location: class MusicControlModule
2 errors

And I get these 2 errors in gradle build output:
...\node_modules\react-native-music-control\android\src\main\java\com\tanguyantoine\react\MusicControlModule.java
error: package android.support.v4.media.app.NotificationCompat does not exist
error: cannot find symbol class MediaStyle

react-native-music-control = 0.9.0
buildToolsVersion = 27.0.3
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = 27.1.1

2. Platform ?

   - [] iOS
   - [x] Android
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by pengcao1** [comment]
add below require
`implementation "com.android.support:support-media-compat:26.1.0"`

**Comment by 13ArturBruno** [comment]
> add below require
> `implementation "com.android.support:support-media-compat:26.1.0"`

Is there a version to use with sdk 27??

**Comment by 13ArturBruno** [comment]
> > add below require
> > `implementation "com.android.support:support-media-compat:26.1.0"`
> 
> Is there a version to use with sdk 27??
 i use:

buildToolsVersion = 27.0.3
compileSdkVersion = 27
targetSdkVersion = 27

But dont work to me ;( can say me a solution ?
