### ISSUE TITLE
No podspec found for `react-native-music-control` in `../node_modules/react-native-music-control

### ISSUE THREAD

**Issue by cattuan** [tanguyantoine/react-native-music-control#201]
# Description
I'm missing error `No podspec found for `react-native-music-control` in `../node_modules/react-native-music-control` when I upgrade version from 0.7.3 to 0.9.0 and  type pod `pod update`.

**Comment by tanguyantoine** [comment]
I'll publish a new version tonight I'll keep you in touch

**Comment by tanguyantoine** [comment]
released as `0.9.2`

**Comment by cattuan** [comment]
@tanguyantoine thanks you!
