### ISSUE TITLE
why the are difference UI between notification and Lockscreen

### ISSUE THREAD

**Issue by pengcao1** [tanguyantoine/react-native-music-control#216]
- [x] Android

  - [x] Notification
![1](https://user-images.githubusercontent.com/40621240/50588424-e29b9b80-0ebc-11e9-88da-f943e0fd295d.jpeg)
- [x] LockScreen
<img width="376" alt="2" src="https://user-images.githubusercontent.com/40621240/50588425-e29b9b80-0ebc-11e9-942b-409ff2f34caa.png">

my question is:
**why the are difference UI between notification and Lockscreen**

**Comment by Guichaguri** [comment]
It's probably your OS identifying a media session and showing what it wants to show. It doesn't happen on stock Android.

**Comment by PromitRai** [comment]
@pengcao1  how did you manage to render controller on locksreen on android ?? Mine only shows the title. Can you give me your code ?

**Comment by 13ArturBruno** [comment]
It's also different for me, Android 8.0. in addition, the play/pause function have a bug.

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
