### ISSUE TITLE
[ios] Not working with WKWebView

### ISSUE THREAD

**Issue by kesha-antonov** [tanguyantoine/react-native-music-control#217]
Hey!

When playing audio in wkwebview the RNMusicControl is not changing behaviour of notification center on lock screen. No image, title and buttons not working.

Please provide some advice!

Seems like this guy have a similar problem. But it was 3 years ago
https://stackoverflow.com/questions/30029338/overriding-mpnowplayinginfocenter-while-using-wkwebview

2. Platform ?

   - [x] iOS
   - [ ] Android
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
```
Although it's impossible to override the property itself on iOS, it should be noted that changing the "title" property of the <video> element in JavaScript

I've achieved this behaviour with

var control = ...; //Create video DOM control
control.title = "Desired title";
```

Have you tried this? From the answer we can't do that

**Comment by kesha-antonov** [comment]
@tanguyantoine Hey!
Yeah, that's kind of progress. But I need a whole control other Info Center - buttons, title, subtitle, image and so on.

**Comment by tanguyantoine** [comment]
can you share a piece of code? you want to retrieve data from the WKWebView view? 

WKWebView can't control the now playing info. if you want to do that, you need to a way to communicate with the content of you web view then, from RN, update playing center.

**Comment by kesha-antonov** [comment]
@tanguyantoine

WKWebView playing html5 audio.
From RN I try to set playing info with RNMusicControl.
It worked with UIWebView. I’ve read that WKWV works in separate process. Maybe that’s why it overrides playing info?

Yeah, I’ll share code, but I think it’s not my code problem.

**Comment by kesha-antonov** [comment]
I’m doing exactly as you say. App communicates from RN with WKVW with onMessage/postMessage. And from RN I try to set playing info.

**Comment by kesha-antonov** [comment]
On lock screen I only see host as title and active play/pause button.
So I think it’s WKWV setting this. And I didn’t find how to prevent WKWV from doing this in Apple documentation.

**Comment by tanguyantoine** [comment]
sorry, I can't help you

**Comment by kesha-antonov** [comment]
@tanguyantoine no worries! Thanks!
We will see maybe somebody could bring the solution
