### ISSUE TITLE
Airpods support?

### ISSUE THREAD

**Issue by tleewu** [tanguyantoine/react-native-music-control#218]
currently, I have my music controller working on the lock screen, but I'd like to be able to skip/rewind 10 seconds using my airpods - does this repo support this?

**Comment by tleewu** [comment]
ah it turns out that you need to enable `nextTrack` and `previousTrack` because that's what the airpods were looking for

**Comment by tanguyantoine** [comment]
Pull Request to update the doc maybe? :-)

with a special section for airpods?

**Comment by tleewu** [comment]
👍
