### ISSUE TITLE
iOS lock screen controls issues

### ISSUE THREAD

**Issue by mojtaba-hajishah** [tanguyantoine/react-native-music-control#223]
# Description

1. Sample code (provide repo url or sample code)
I can't share my repo because of NDA stuff.
I'm using react native video for my player, and this repo for music controls.
Music controls are working on android. but on iOS, I have multiple issues.

**on simulator**
1) music controls do not appear on simulator lock screen at all

**on real device**
1) music controls appear, but elapsed time and remaining time appear and disappear randomly when I change the now playing track. (mostly disappeared)
2) when I pause the music, elapsed time resets to 0.

**code**
```
componentDidMount() {
  musicControlConfig() {
    MusicControl.enableBackgroundMode(true);
    MusicControl.handleAudioInterruptions(true);
    MusicControl.enableControl("play", true);
    MusicControl.enableControl("pause", true);
    MusicControl.enableControl("nextTrack", false);
    MusicControl.enableControl("previousTrack", false);
    MusicControl.on("play", () => {
      this.play();
    });
    MusicControl.on("pause", () => {
      this.pause();
    });
    MusicControl.on("nextTrack", () => {
      this.next();
    });
    MusicControl.on("previousTrack", () => {
      this.prev();
    });
  }
}
```

_every time the track changes, this method is called:_

```
musicControlInit(newTrack) {
    MusicControl.setNowPlaying({
      title: newTrack.title,
      artwork: newTrack.header_image_url || require("../assets/img/logo.png"),
      artist: newTrack.artists,
      duration: this.state.duration
    });
  }
```
_play method:_

```
  play = () => {
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PLAYING,
        elapsedTime: this.state.elapsedTime
      });
    }
  };
```
_same logic goes for pause(), next() and prev()._

**Info**
react-native-music-control: "0.9.7"
react: "16.3.1"
react-native: "0.55.3"
react-native-video: "4.3.1"

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
> music controls do not appear on simulator lock screen at all
That's normal, simulator is a special snowflake not working exactly the same way as a real device.

What your `pause` method looks like?

**Comment by chiaberry** [comment]
I'm having a similar issue, but in my case the elapsed time counts how long the music controls have been up, but when I hit pause the elapsed time jumps to the correct time. 
@mojtaba-hajishah  were you able to fix it?

**Comment by mojtaba-hajishah** [comment]
@chiaberry Nope, still waiting for a fix or sth from @tanguyantoine .

**Comment by chiaberry** [comment]
I tried setting `elapsedTime` in `setNowPlaying` and it (so far) appears to help

https://github.com/tanguyantoine/react-native-music-control/issues/186#issuecomment-435660865

**Comment by mojtaba-hajishah** [comment]
@chiaberry thanks a lot.
Always using setNowPlaying() instead of updatePlayback() fixed the issue for me.
But I think it should be resolved in the next versions of this library.

**Comment by tanguyantoine** [comment]
Update playback should definitely be updated to the correct behavior ^^
