### ISSUE TITLE
How to jump to the next track automatically on the ios lock screen?

### ISSUE THREAD

**Issue by 13ArturBruno** [tanguyantoine/react-native-music-control#226]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

------------------

...
MusicControl.on('nextTrack', this.next)
...
MusicControl.enableControl('nextTrack', true)
...
next = () => {
        this.pause()
        this.otherAudio(item)    //item i take inside this code
        }
};
...

!!

**Comment by tanguyantoine** [comment]
please elaborate (whatever your language is)

**Comment by tanguyantoine** [comment]
@13ArturBruno what was the issue?

**Comment by 13ArturBruno** [comment]
Just use MusicControl.enableControl('changePlaybackPosition', true) kk resolve my problem
