### ISSUE TITLE
Toggling "play" also starts the SoundCloud app

### ISSUE THREAD

**Issue by jasongrishkoff** [tanguyantoine/react-native-music-control#23]
Real Android device (Nexus 5x w/ Android 7.1.1)

If I pause my song using:
`MusicControl.on('pause',` ()=> { this.playPause() })`

Firing the app up again with the following also causes my SoundCloud app to start playing again:
`MusicControl.on('play',` ()=> { this.playPause() })`

I'm wondering if they both use ExoPlayer and it's somehow linked to that?

**Comment by rikochet** [comment]
I'm experiencing a similar issue..

The first time I play/pause VLC will start playing, and the second time Spotify will start.

Looking through the docs I thought [getSessionToken](https://github.com/tanguyantoine/react-native-music-control/blob/a8d22e324700686d84e78615b292ee136b45e817/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java#L83) was supposed to protect against this..

**Comment by AshkanValadkhani** [comment]
same issue here ( same as @rikochet  ) and volume button not working

**Comment by jasongrishkoff** [comment]
Yeah, volume button doesn't work for me, but I had assumed that was related to another issue and was still planning to look into it.  Looks like perhaps it's related to MusicControl.  I'll dig deeper, and if so include it in another open issue :)

**Comment by jasongrishkoff** [comment]
Update: first resume after pause starts SoundCloud; if I pause and then play a second time, it launches Spotify.

**Comment by rikochet** [comment]
@AshkanValadkhani 

I don't fully understand what `setPlaybackToRemote` does, so I just swapped it out for `setPlaybackToLocal` and used AudioManager, now the audio controls work fine.

Example;
```session.setPlaybackToLocal(AudioManager.STREAM_MUSIC);```

**Comment by ahmedlhanafy** [comment]
I have this one as well pressing playing triggers all of music apps to play

**Comment by jasongrishkoff** [comment]
A bit stumped on this one right now -- anyone else figure it out?

**Comment by rikochet** [comment]
I wasted most of my christmas holiday trying to figure out what was causing this issue and eventually came to the conclusion that issue is with [session.getController().dispatchMediaButtonEvent(ke);](https://github.com/tanguyantoine/react-native-music-control/blob/master/android/src/main/java/com/tanguyantoine/react/MusicControlReceiver.java#L30)..

I couldn't figure out why other apps were conflicting with the dispatchMediaButtonEvent so in the end I resorted to creating actions which use the library namespace instead of PlaybackStateCompat.

You can find a working branch [here](https://github.com/tanguyantoine/react-native-music-control/compare/master...rikochet:alt-media-actions), it's not pretty, but it works ;-)

**Comment by jasongrishkoff** [comment]
Interesting!  Do you know how that effects usage of media buttons on your headphones or whatever else one might use?  Would actually be great to compare notes on what you're building and what I'm building -- I've managed to hook up some background interaction stuff using React Native's HeadlessJS so that folks can continue to use the app while it's in the background. Feel free to email me on jason [at] indieshuffle.com :)

**Comment by tanguyantoine** [comment]
I'm not sure it is a problem with this package.

**Comment by jasongrishkoff** [comment]
I'm quite confident it is in fact an issue with this package. I also built
my own NotificationCompat service and had no similar issues.

**Comment by tanguyantoine** [comment]
Sorry I'm not an Android developer, @Guichaguri any thoughts ?

**Comment by Guichaguri** [comment]
It doesn't work because I thought using Android media controls keys was a good idea for the notification buttons.
I'll fix it soon, and to not make the same mistake, I'll have to create media keys based on the app name to prevent conflict with other apps using the same package

**Comment by jasongrishkoff** [comment]
Cool thank you @Guichaguri!  @rikochet, I tried yours and it does indeed solve the issue, though I notice that for some reason it fixes 5x on each event?

**Comment by cinder92** [comment]
same issue here! it starts all my music player apps

**Comment by tanguyantoine** [comment]
@jasongrishkoff is it something you can add in this repo ?

**Comment by jasongrishkoff** [comment]
@rikochet's solution worked for me - perhaps we should use that?

**Comment by tanguyantoine** [comment]
Pull request ? :)

**Comment by jasongrishkoff** [comment]
I don't know how (eeek, sorry!), but here's his branch: https://github.com/tanguyantoine/react-native-music-control/compare/master...rikochet:alt-media-actions

**Comment by tanguyantoine** [comment]
@rikochet can I let you do that ?

**Comment by Guichaguri** [comment]
Using `setPlaybackToLocal` should be just a temporary fix, as it also breaks a bunch of other things.
I'm currently testing the fix for this and #25, I'll open a PR soon :)
