### ISSUE TITLE
Error: setShowActionsInCompactView

### ISSUE THREAD

**Issue by vortgo** [tanguyantoine/react-native-music-control#230]
Hello. 
I try to use this package for my project but every time I catch error: 
**`setShowActionsInCompactView: action 0 out of bounds (max -1)`**

My code is from demo app:
```
MusicControl.enableBackgroundMode(true);
MusicControl.setNowPlaying({
      title: 'Billie Jean',
      artwork: 'https://i.imgur.com/e1cpwdo.png',
      artist: 'Michael Jackson',
      album: 'Thriller',
      genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
      duration: this.whoosh.getDuration(),
      description: 'Billie Jean is a song by American singer Michael Jackson. It is the second single from the singer\'s sixth solo album, Thriller (1982). It was written and composed by Jackson and produced by Jackson and Quincy Jones.',
      date: '1983-01-02T00:00:00Z',
      rating: 84
    })
    MusicControl.enableControl('play', false)
    MusicControl.enableControl('pause', true)
```

I have reduced the code to simple invoke:
```
MusicControl.setNowPlaying({
      title: 'Billie Jean',
})
```
But the error is still throwing. 
Then I have tried run demo project `https://github.com/tanguyantoine/react-native-music-control-demo` as it is and again I failed with the same error

I have found a lot of projects using this package and code is familiar with mine. 
Could any give me a hint where I make mistake?

**Comment by Guichaguri** [comment]
This was caused by #227. That's what happens when you merge a commit without reviewing it or at least testing it properly.

**Comment by tanguyantoine** [comment]
Can you elaborate on the reasons of this issue?

**Comment by Guichaguri** [comment]
Basically, you can use `setShowActionsInCompactView` to specify which actions will be visible when the notification is collapsed. The commit in #227 hardcodes the first three actions, if you have less than those three buttons enabled, it will crash.

I don't know how a hardcoded array such as the `new int[]{0,1,2}` passes a code review.

**Comment by vortgo** [comment]
I just use the previous version. Thanks for the explanation.

**Comment by tanguyantoine** [comment]
Maybe because I have no knowledges on Android ;-)
I’ll revert it
