### ISSUE TITLE
Crash on Android 9: java.lang.SecurityException MusicControlNotification$NotificationService.onCreate

### ISSUE THREAD

**Issue by jamsch** [tanguyantoine/react-native-music-control#235]
# Description

Ran a deploy using the latest version of this library and it seems to crash while starting the app on Android 9 devices. So far the past hour I've received a large number of these reports so I'm having a look in to the cause now.

2. Platform

   - [ ] iOS
   - [x] Android
   
3. Device
  - [ ] Simulator
  - [x] Real device

![selection_023](https://user-images.githubusercontent.com/12927717/52976858-00eb3580-3430-11e9-80c1-79dab4e7518e.png)

**Comment by jamsch** [comment]
Looks like `android.permission.FOREGROUND_SERVICE` may need to be added to the AndroidManifest for apps that target Android 9

https://developer.android.com/guide/components/services#Foreground

**Comment by andrewazevedo** [comment]
Adding `android.permission.FOREGROUND_SERVICE` works fine for me too.

**Comment by tanguyantoine** [comment]
Mays ask one of you (@andrewazevedo or @jamsch) to create a PR to add either documentation or update the code if needed?
