### ISSUE TITLE
closeNotification not working

### ISSUE THREAD

**Issue by gfpacheco** [tanguyantoine/react-native-music-control#236]
# Description

I'm unable to dismiss the notification at all. I tried enabling it `always` and `paused`, but neither options work.

1. Sample code (provide repo url or sample code)

I don't think there's anything special about my code, I added a listener for when the notification is closed:

```
MusicControl.on('closeNotification', this.stop)
```

And enabled it:

```
MusicControl.enableControl('closeNotification', true, { when: 'paused' })
```

2. Platform ?

   - [ ] iOS
   - [x] Android
   
3. Device

   - [x] Simulator
   - [x] Real device

**Comment by Faisal-Manzer** [comment]
Facing same issue.
![screenshot 2019-02-22 at 2 55 14 am](https://user-images.githubusercontent.com/18066439/53202749-52bcd700-364d-11e9-9d21-ec068a9cf116.png)

```js
    MusicControl.enableControl('closeNotification', true, {when: 'always'});
```

Can't remove notification.

**Comment by brennan-pilcher** [comment]
I'm able to swipe to dismiss the notification, but only if it is in the paused state, regardless of if I call enableControl with `{when: 'always'}` or `{when: 'paused'}`. Also, the event listener for closeNotification does not appear to trigger when swiping to dismiss the notification.

**Comment by matinzd** [comment]
I have the same issue on android tested with all actions and devices !

**Comment by tom-krusch** [comment]
I still have this error, no matter what configuration, I cannot close the notification!
