### ISSUE TITLE
MusicControl enableControl stop

### ISSUE THREAD

**Issue by GH974** [tanguyantoine/react-native-music-control#239]
# Description
hi, how it works function MusicControl.enable Control It doesn't show on the lock screen
1. Sample code (provide repo url or sample code)
MusicControl.enableControl('stop', true);

2. Platform ?

   - [X ] iOS
   - [X ] Android
   
   
3. Device
  - [ X] Simulator
  - [ X] Real device

**Comment by tanguyantoine** [comment]
Please add more details. Feel free to use your native language

**Comment by GH974** [comment]
How its works MusicControl.enableControl('stop', true);
is not appear in lock screen.
In lockscreen i have next/prev and play/pause button and not stop button ?

**Comment by tanguyantoine** [comment]
on both platform?

**Comment by GH974** [comment]
in ios

**Comment by GH974** [comment]
i have not tested for android sorry.

**Comment by GH974** [comment]
Hi, in android this bug is present.
I tested in version api 28

has bug if add ligne commande
`   MusicControl.enableControl('play', true);
`

ADB LOGCAT RESULT

```
04-29 13:10:42.135  4669  4669 E AndroidRuntime: Process: com.radiosreunion, PID: 4669
04-29 13:10:42.151  1886  1903 I ActivityManager: Showing crash dialog for package com.radiosreunion u0
04-29 13:10:42.160  4669  4690 I FA      :   adb shell setprop debug.firebase.analytics.app com.radiosreunion
04-29 13:10:50.879  1886  1902 W ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{e342fa0 u0 com.radiosreunion/com.tanguyantoine.react.MusicControlNotification$NotificationService}
04-29 13:10:50.906  1886  1902 I ActivityManager: Crashing app skipping ANR: ProcessRecord{cd3ce8d 4669:com.radiosreunion/u0a93} Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e342fa0 u0 com.radiosreunion/com.tanguyantoine.react.MusicControlNotification$NotificationService}
```

**Comment by GH974** [comment]
Finally i found this bug. In version api 28 of android, is needed to add permission FOREGROUND_SERVICE in androidManifest.xml

**Comment by tanguyantoine** [comment]
Could you update the reader?

**Comment by GH974** [comment]
Sorry i don't understand

**Comment by tanguyantoine** [comment]
Is, what you said previously in the readme of the repository? If not then I’ll appreciate your contribution :-)

**Comment by GH974** [comment]
No i found in https://developer.android.com/about/versions/pie/android-9.0-changes-28

**Comment by gazedash** [comment]
@tanguyantoine I have the same crash as @GH974 , and I enabled FOREGROUND_SERVICE permissions
