### ISSUE TITLE
Android: Notification onClick event does nothing

### ISSUE THREAD

**Issue by rikochet** [tanguyantoine/react-native-music-control#24]
When clicking the notification during playback you'd expect the app UI to be presented to the user but instead nothing happens.

I imagine it's something around [here](https://github.com/tanguyantoine/react-native-music-control/blob/master/android/src/main/java/com/tanguyantoine/react/MusicControlNotification.java#L52) that needs modifying.

**Comment by tanguyantoine** [comment]
Are you able to do a PR to fix that ?
