### ISSUE TITLE
Closing app on Android 8.0 (Possibly only Huawei phones) when setNowPlaying is called

### ISSUE THREAD

**Issue by ali-pedram** [tanguyantoine/react-native-music-control#241]
when set the code provided below is called after the sound is loaded and starts to play (using react-native-sound) the app closes. the affected devices are all running android 8.0 and manufactured by Huwawei.

1. Sample code (provide repo url or sample code)

                            MusicControl.enableControl('play', true)
                            MusicControl.enableControl('pause', true)
                            MusicControl.enableControl('nextTrack', true)
                            MusicControl.enableControl('previousTrack', true)
                            MusicControl.enableControl('seekForward', true) // iOS only
                            MusicControl.enableControl('seekBackward', true) // iOS only
                            MusicControl.enableControl('skipForward', true, {interval: 30})
                            MusicControl.enableControl('skipBackward', true, {interval: 10})
                            MusicControl.enableControl('closeNotification', true, { when: 'always' })
                            MusicControl.setNowPlaying({
                                title: 'sample title',
                                artist: 'sample artist',
                                artwork: params.productCover,
                                duration: parseInt(this.sound.getDuration()),
                                description: '',
                                state: MusicControl.STATE_PLAYING,
                                speed: 1,
                                elapsedTime: 0
                            })

2. Platform ?

 Android
   
3. Device

Real device

**Comment by tanguyantoine** [comment]
do you have crash logs you could share?

**Comment by ali-pedram** [comment]
The app doesn't actually crash. so it produces no error on react native debugger console. but here's the error shown on my app analytics:
Bad notification posted from package com.app: Couldn''t expand RemoteViews for: StatusBarNotification(pkg=ir.sabketoplus.app user=UserHandle{0} id=100 tag=null key=0|com.app|100|null|10143: Notification(channel=react-native-music-control pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=transport vis=PRIVATE))
And here is the stack trace:
android.app.ActivityThread$H@handleMessage(File:ActivityThread.java:2204)
android.os.Handler@dispatchMessage(File:Handler.java:108)
android.os.Looper@loop(File:Looper.java:166)
android.app.ActivityThread@main(File:ActivityThread.java:7523)
java.lang.reflect.Method@invoke(File:Method.java:-2)
com.android.internal.os.Zygote$MethodAndArgsCaller@run(File:Zygote.java:245)
com.android.internal.os.ZygoteInit@main(File:ZygoteInit.java:921)
From what i could gather this error is related to the images displayed in the notification which are vector drawables

**Comment by 13ArturBruno** [comment]
Mine also happened to close, I discovered that any error or library depreciated forced to close. check it.

**Comment by arondn2** [comment]
Hi, guys.

I had the same issue and I resolved it adding the permission `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in the AndroidManifest.xml.

Regards.
