### ISSUE TITLE
Use for detect headphone buttons event

### ISSUE THREAD

**Issue by gollkn** [tanguyantoine/react-native-music-control#243]
# Description
Hello, I am trying to detect when user click play/pause button from headphone, I only have this code. I don't want start some music or media and then detect, if there are some way to listen headphone events without playing media ?

1. Sample code (provide repo url or sample code)
`componentDidMount() {
    MusicControl.enableBackgroundMode(true);

        // on iOS, pause playback during audio interruptions (incoming calls) and resume afterwards.
        MusicControl.handleAudioInterruptions(true);

        MusicControl.on('play', ()=> {
            console.log('play.log');
            // this.props.dispatch(playRemoteControl());
        })

        // on iOS this event will also be triggered by audio router change events
        // happening when headphones are unplugged or a bluetooth audio peripheral disconnects from the device
        MusicControl.on('pause', ()=> {
            console.log("pause");
            // this.props.dispatch(pauseRemoteControl());
        })

        MusicControl.on('stop', ()=> {
            console.log("stop");
        });

}`

2. Platform ?

   - [x] iOS
   - [x] Android
   
   
3. Device
  - [x] Real device

**Comment by nishiltamboli** [comment]
I have the same issue. On iOS, the Pause and Play events are not called when the headphone button for play pause is pressed. Also I couldn't receive callback in togglePlayPause listener as well. Seems that the event is not going through somehow!

**Comment by tomsvogel** [comment]
@nishiltamboli @gollkn  did you find a solution for this?

**Comment by jetobe95** [comment]
Hello 👋🏼 @gollkn any solution ?
