### ISSUE TITLE
Pause button does not show up after being enabled on Android

### ISSUE THREAD

**Issue by brennan-pilcher** [tanguyantoine/react-native-music-control#245]
# Description

The pause button does not show up in the Music Control notification on Android after calling MusicControl.enableControl('pause', true).

I noticed this in my main project and then created a pared down version based on [the demo project](https://github.com/tanguyantoine/react-native-music-control-demo) in order to validate that it was an issue with this repo instead of my own code.

1. Sample code (provide repo url or sample code)

```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import MusicControl from 'react-native-music-control';

export default class App extends React.Component {
  constructor(props){
    super(props)
  }

  componentDidMount(){
    MusicControl.enableControl('play', true)
    MusicControl.enableControl('pause', true)

    MusicControl.setNowPlaying({
      title: 'title',
      artwork: 'https://i.imgur.com/e1cpwdo.png',
      artist: 'artist',
      album: 'album',
      genre: 'genre',
      duration: 100,
      description: 'description',
      date: '1983-01-02T00:00:00Z',
      rating: 84
    })
  }

  render() {
    return (
      <View style={styles.container}>
        <Button
          onPress={() => {}}
          title="PLAY SONG"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by brennan-pilcher** [comment]
We were able to figure out the issue. It appears that you need to call MusicControl.updatePlayback and set the state to MusicControl.STATE_PLAYING, at which point the play icon automatically turns into a pause icon. It would be great if this could be detailed in the documentation! I can open a PR explaining this flow if that would be helpful.

**Comment by tanguyantoine** [comment]
please do 🙏
