### ISSUE TITLE
custom notification bar onPress event

### ISSUE THREAD

**Issue by ammoradi** [tanguyantoine/react-native-music-control#246]
# Description

Is there any way to create a custom onPress event on notification bar?
for example, I need to navigate to a dynamic route based on current playing sound when I tap on the notification bar.

1. Sample code
needed: `MusicControl.setBarOnPress(this.props.navigation.navigate(' somewhere '))`

2. Platform
   - [x] iOS
   - [x] Android
   
3. Device
   - [x] Simulator
   - [x] Real device

**Comment by tanguyantoine** [comment]
What do you mean by notification? I think it is you app responsibility to handle notifications. 
You'll have to add extra information into the notification and then register the correct handler.
Sorry, it's not the intent of this library

**Comment by ammoradi** [comment]
notification bar = music player bar on top

**Comment by nisheetsun** [comment]
I have the same question. By default on click of react-native-music-control notification redirects to the home page of the app.
