### ISSUE TITLE
Android: Volume buttons unresponsive

### ISSUE THREAD

**Issue by rikochet** [tanguyantoine/react-native-music-control#25]
During playback volume buttons are unresponsive.

If I replace `session.setPlaybackToRemote()` with `session.setPlaybackToLocal()` and use Android's `AudioManager` I can circumvent this issue.

If I'm honest don't actually know the purpose of `setPlaybackToRemote()` .. Is it something to do with `MediaRouter`?

**Comment by tanguyantoine** [comment]
Sorry I'm not an Android developer, @Guichaguri any thoughts ?

**Comment by Guichaguri** [comment]
The reason why I use `setPlaybackToRemote` is to make it work with chromecast and other external devices.
It might be a good idea to also add an option to use `setPlaybackToLocal`...
I'll take a look when I have time :)

**Comment by Guichaguri** [comment]
The remote volume has been fixed and there's a `remoteVolume` option which is disabled by default
