### ISSUE TITLE
bug event stop function

### ISSUE THREAD

**Issue by GH974** [tanguyantoine/react-native-music-control#256]
# Description
I found a bug if i add enableControl('stop').
Function event MusicControl.on('stop') is called once on play music.
but I not called MusicControl.setNoPlaying or MusicControl.updatePlayback function.
 After this, I just play music in react native video

1. Sample code (provide repo url or sample code)
no code exemple

2. Platform ?

   - [ ] iOS
   - [x] Android 9 api 28
   
   
3. Device
  - [x ] Simulator
  - [ ] Real device

**Comment by SwiftyWang** [comment]
Same issue found in Android device

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
