### ISSUE TITLE
Resuming play after pausing not working with expo-av 

### ISSUE THREAD

**Issue by redpandatronicsuk** [tanguyantoine/react-native-music-control#257]
# Description
I'm experiencing an issue with `react-native-music-control` and `expo-av`. I have already created an issue on the `expo` repository (https://github.com/expo/expo/issues/4171). I have made a reproducible demo here: https://github.com/redpandatronicsuk/expoavtest

When `staysActiveInBackground` is set to `true`, in the `expo-av` configuration, the audio keeps playing even when in background mode. The lockscreen controls show up when the device is locked and pressing the pause the first time works. The icon changes to the play icon, as expected, but when pressing the play button nothing happens. In the Xcode console this is logged when the play button is pressed: `Error: Play encountered an error: audio session not activated.`. In `expo-av` there is a function (https://github.com/expo/expo/blob/491dde5dedca1a95efa40026aa119a0b0ec2b4e5/packages/expo-av/ios/EXAV/EXAVPlayerData.m#L359) which returns whether the player is playing or not. Having that function always return `true` seems to fix that issue, i.e. the play button on the lockscreen works too.

However, that fix/workaround doesn't seem right and the function should return `false` when the player is paused, I suppose. What would be the correct way to keep the audio session active when the player is paused from the lockscreen controls?

1. Sample code (provide repo url or sample code)
https://github.com/redpandatronicsuk/expoavtest

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by redpandatronicsuk** [comment]
I just updated the dependencies the the repo with the sample code for this issue (https://github.com/redpandatronicsuk/expoavtest) now using `expo-av: 5.0.0` and `react-native-music-control: 0.10.4` and the issue persists.

**Comment by EyyupUlutas** [comment]
@redpandatronicsuk Is there a solution to this issue?

**Comment by cmlarsen** [comment]
I also am having this issue
`react-native-music-control@0.10.7`

**Comment by tanguyantoine** [comment]
dis you eject the expo app? I think the issue is related to expo.

**Comment by cmlarsen** [comment]
In my case my app isn't  an expo app but a standalone RN app.

**Comment by tanguyantoine** [comment]
can you retry with the latest version?

**Comment by redpandatronicsuk** [comment]
@tanguyantoine thanks for looking into this. For me resuming, once paused from the lock screen, still doesn't work with the latest versions of `react-native-music-control ` and `expo-av`. I found a workaround I posted here: https://github.com/expo/expo/issues/4171
Do you think the workaround is *correct* or just a patch for this particular problem but principally still flawed?

**Comment by cassiossantos** [comment]
Same problem in Android
