### ISSUE TITLE
use redux on event

### ISSUE THREAD

**Issue by GH974** [tanguyantoine/react-native-music-control#258]
# Description
In android, on the lockscreen, the button action, play, pause,  does not work. It work if app is opened and i use button action in notification screens.

1. Sample code (provide repo url or sample code)
I use redux in my app, and MusicControl.event code is in app.js and get redux action in my another component VideoPlayer.js
```
MusicControl.on('nextTrack', () => {
            this.props.onAction({status:"next", id:Math.floor(Math.random() * Math.floor(100000000))});
});
```

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by GH974** [comment]
I found this bug. i use setTimeout function, and it doesn't work in background mode. Why ?

**Comment by roffelund** [comment]
I believe there is often issues when using setTimeout functions in backround mode. Have you tried not using setTimeout or possibly something like https://www.npmjs.com/package/react-native-background-timer.

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
