### ISSUE TITLE
A new instance of app is getting created on click of push notification.

### ISSUE THREAD

**Issue by nisheetsun** [tanguyantoine/react-native-music-control#262]
Every time I click on the notification, it launches a new instance of App and navigates to the first/splash screen instead of navigating to the last visited screen. The issue that it causes is that the old component has not yet been unmounted and a new one gets created on top of that. I am using react-native-video(with playInBackground as true), every time I click in notification it launches the app again and multiple instances if the same component gets created as a result same media is getting played concurrently multiple times.

```
MusicControl.enableControl('play', true)
        MusicControl.enableControl('pause', true)
        // MusicControl.enableControl('stop', true)
        MusicControl.enableBackgroundMode(true);
        MusicControl.enableControl('nextTrack', true)
        MusicControl.enableControl('previousTrack', true)
        MusicControl.enableControl('closeNotification', true, { when: 'paused' })
        MusicControl.on('play', () => {
            this.play()
        });
        MusicControl.on('pause', () => {
            this.pause()
        });

        MusicControl.updatePlayback({
            state: MusicControl.STATE_PLAYING,
            elapsedTime: 135
        })

```
         MusicControl.setNowPlaying({
            title: this.title,
            artwork: this.poster,
            artist: 'Michael Jackson',
            album: 'Thriller',
            genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
            duration: this.duration, // (Seconds)
            description: '', // Android Only
            color: 0xFFFFFF, // Notification Color - Android Only
            date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
            rating: 84, // Android Only (Boolean or Number depending on the type)
            notificationIcon: 'my_custom_icon' // Android Only (String), Android Drawable resource name for a custom notification icon
        })

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by Raghukamc** [comment]
Same here

**Comment by Raghukamc** [comment]
Add this code in AndroidManifest.xml. It works for me
<activity
  android:name=".MainActivity"
  android:launchMode="singleTask">

https://facebook.github.io/react-native/docs/linking

**Comment by tanguyantoine** [comment]
@Raghukamc  would you mind creating a PR explaining what to do?

**Comment by alanperius** [comment]
> Every time I click on the notification, it launches a new instance of App and navigates to the first/splash screen instead of navigating to the last visited screen. The issue that it causes is that the old component has not yet been unmounted and a new one gets created on top of that. I am using react-native-video(with playInBackground as true), every time I click in notification it launches the app again and multiple instances if the same component gets created as a result same media is getting played concurrently multiple times.
> 
> ```
> MusicControl.enableControl('play', true)
>         MusicControl.enableControl('pause', true)
>         // MusicControl.enableControl('stop', true)
>         MusicControl.enableBackgroundMode(true);
>         MusicControl.enableControl('nextTrack', true)
>         MusicControl.enableControl('previousTrack', true)
>         MusicControl.enableControl('closeNotification', true, { when: 'paused' })
>         MusicControl.on('play', () => {
>             this.play()
>         });
>         MusicControl.on('pause', () => {
>             this.pause()
>         });
> 
>         MusicControl.updatePlayback({
>             state: MusicControl.STATE_PLAYING,
>             elapsedTime: 135
>         })
> ```
> 
> ```
>      MusicControl.setNowPlaying({
>         title: this.title,
>         artwork: this.poster,
>         artist: 'Michael Jackson',
>         album: 'Thriller',
>         genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
>         duration: this.duration, // (Seconds)
>         description: '', // Android Only
>         color: 0xFFFFFF, // Notification Color - Android Only
>         date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
>         rating: 84, // Android Only (Boolean or Number depending on the type)
>         notificationIcon: 'my_custom_icon' // Android Only (String), Android Drawable resource name for a custom notification icon
>     })
> ```
> 
> 1. Platform ?
>    
>    * [ ]  iOS
>    * [x]  Android
> 
> 1. Device
> 
> * [ ]  Simulator
> * [x]  Real device

Hi @nisheetsun i'm getting the same problem... i don't know how to fix it. adding:
<activity
  android:name=".MainActivity"
  android:launchMode="singleTask">

on manifest do not worked =(

**Comment by The0racle** [comment]
Android manifest.

![image](https://user-images.githubusercontent.com/4213174/59055657-34b96200-884b-11e9-97cf-cbf4f6c4b9ee.png)

**Comment by tanguyantoine** [comment]
@The0racle can you create a PR to explain this tricks? 🙏

**Comment by bradleyflood** [comment]
This will be fixed in #327

**Comment by murtuzamacdev** [comment]
> Android manifest.
> 
> ![image](https://user-images.githubusercontent.com/4213174/59055657-34b96200-884b-11e9-97cf-cbf4f6c4b9ee.png)

This is did not work for me.

**Comment by bradleyflood** [comment]
Fixed in next release via https://github.com/tanguyantoine/react-native-music-control/pull/383 😄
