### ISSUE TITLE
Handle Audio Interruptions with instagram app [Android]

### ISSUE THREAD

**Issue by rreiser-auti** [tanguyantoine/react-native-music-control#264]
# Description
When the app is opened and the state is paused, i touch play button in a video on instagram app, then i pause the instagram video, my app starts to play by itself. 

1. Sample code (provide repo url or sample code)
MusicControl.handleAudioInterruptions(true);

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by roffelund** [comment]
This would be because as soon as the app gains audioFocus it tries to play.

```} else if (focusChange == AudioManager.AUDIOFOCUS_GAIN) {
            if (volume.getCurrentVolume() != 100) {
                volume.setCurrentVolume(100);
            }
            emitter.onPlay();
 }```

Not really sure how to combat this. Since if you have a AUDIOFOCUS_LOSS_TRANSIENT then the app pauses and to make it play again we need to use the onPlay.

**Comment by lucasrocali** [comment]
I've created a PR 
https://github.com/tanguyantoine/react-native-music-control/pull/308

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
