### ISSUE TITLE
setNowPlaying fails on each fresh app launch

### ISSUE THREAD

**Issue by brettdh** [tanguyantoine/react-native-music-control#270]
# Description

When I install my app with `react-native run-ios`, or if I force-quit and relaunch the app, when I tap a button which results in calling `MusicControl.setNowPlaying` followed by `MusicControl.updatePlayback`, the app controls don't display.

If I then refresh the javascript bundle with command-R and repeat the above actions, the app controls _do_ display. But, if I reinstall the app or force-quit and relaunch as above, the controls don't display.

1. Sample code (provide repo url or sample code)

Not exactly a minimal example, but here's an app I'm working on that exhibits the above behavior. All the `MusicControl` invocations are in this file: https://github.com/theliturgists/app/blob/master/src/state/ducks/playback/epic.js

Let me know if further explanation is needed.

2. Platform ?

   - [x] iOS 12.2
   - [ ] Android
   
3. Device
  - [x] Simulator
  - [ ] Real device

**Comment by brettdh** [comment]
Cannot reproduce on my iPhone X, iOS 12.3.1. Haven't yet been able to get iOS 12.3.1 running in the simulator, so I'm not sure if it's a simulator issue or an iOS 12.2 issue.

**Comment by brettdh** [comment]
FWIW, I also could not reproduce the issue on the Android emulator.

**Comment by sfreeman28** [comment]
I have the same issue. Simulator running 12.2.
Can confirm Android Emulator not an issue.

I have not tested on a real iPhone yet.
Did you find any solution for iOS?
Regards

**Comment by brettdh** [comment]
@sfreeman28 nope; I've never seen it on my real iOS device, and I haven't pressed further into the iOS version issue on the simulator.

**Comment by sfreeman28** [comment]
@brettdh Ok thanks. Appreciate the fast reply.

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
