### ISSUE TITLE
Notification bar continue to show when app is closed

### ISSUE THREAD

**Issue by sefatamak** [tanguyantoine/react-native-music-control#276]
I want to close notification bar when app is closed by user but when I close the app completely, notification bar continue. How can I solve it ?
2. Platform ?
   - Android
   
3. Device
  - Real Device (LG G4)

**Comment by mojtaba-hajishah** [comment]
Same for me on Android 5.

**Comment by sfreeman28** [comment]
I noticed this issue too. It also can affect devices running Android O (28).

You can reproduce by calling `resetNowPlaying` which hides the notification (and kills the foreground service on O), then call `setNowPlaying` again to show the notification, and then swipe the app away to kill it. The second notification is still visible.

The way I fixed this for Android O was to change the start of the `initi` method in MusicControlModule to:
```
    public void init() {
        if (init) {
            // ensure service is running incase it was stopped from resetNowPlaying or stopControl
            Intent myIntent = new Intent(context, MusicControlNotification.NotificationService.class);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) context.startForegroundService(myIntent);
            else context.startService(myIntent);
            return;
        }
        ... // rest of method
```

It ensures the foreground service is always restarted if needed.

Unfortunately this doesn't seem to fix the notification still showing after killing app on below API 28.
Anyone found a fix for that yet?
Thanks

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
