### ISSUE TITLE
Build fails on RN 0.40

### ISSUE THREAD

**Issue by dnish** [tanguyantoine/react-native-music-control#28]
# Description

I'm getting the following error after adding and linking the package:

```
/Users/dennis/Desktop/Entwicklung/musica/musica_app/android/app/src/main/java/com/musica_app/MainApplication.java:7: error: cannot find symbol
import com.tanguyantoine.MusicControl.MusicControl;
                                     ^
  symbol:   class MusicControl
  location: package com.tanguyantoine.MusicControl
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```
I've just run <code>react-native link react-native-music-control</code> and can validate that all links where created (if I compare them with the manual steps).

2. Platform
   - [ ] iOS
   - [ x] Android
   
   
3. Device
  - [ ] Simulator
  - [x ] Real device

**Comment by tanguyantoine** [comment]
Did you add it manually ?

**Comment by tanguyantoine** [comment]
You should have `import com.tanguyantoine.react.MusicControl; ` instead

**Comment by tanguyantoine** [comment]
can you check ?

**Comment by dnish** [comment]
@tanguyantoine Yep, the import path was wrong. I didn't add it manually, It was added by the linking command.

<code>import com.facebook.react.ReactApplication;</code> would be correct.

**Comment by tanguyantoine** [comment]
Hum weird are you able to do a PR to fix that ?

**Comment by dnish** [comment]
Uff, I have to admit that I'm really new on React Native and don't know how <code>react-native links</code> internally, the only thing that I saw is in https://github.com/tanguyantoine/react-native-music-control/blob/master/android/src/main/AndroidManifest.xml 

I'm just wondering if the package name should be <code>com.tanguyantoine.react.MusicControl</code>

**Comment by tanguyantoine** [comment]
I updated the manifest and published on npm, can you try with the version `0.2.3`

**Comment by shshaw** [comment]
I'm getting the following error with react-native-music-control 0.3.0

```
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/stephen.shaw/Sites/NGEN/android/app/src/main/java/com/ngen/MainApplication.java:31: error: cannot find symbol
            new MusicControlPackage(),
                ^
  symbol: class MusicControlPackage
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception. 
```

**Comment by tanguyantoine** [comment]
@shshaw any ideas ?

**Comment by shshaw** [comment]
Actually, scratch that. Sorry. I was attempting to debug on a previous version before updating and was making chances to the `import` statement, and changed the `getPackages` list to try to resolve another error. Changing it back to `new MusicControl()` seems to have worked.

I'm getting some different errors now, but the application does compile and runs in the emulator so I'll be checking my code to see how I need to configure MusicControl for Android.
