### ISSUE TITLE
Add support for React Native 0.60, specifically androidx support libraries

### ISSUE THREAD

**Issue by timmywil** [tanguyantoine/react-native-music-control#280]
# Description

Build a new project with `react-native init`, include react-native-music-control, and try to build in Android. The build fails with error `ERROR: Unable to resolve dependency for ':react-native-music-control@debug/compileClasspath': Could not resolve androidx.core:core:{strictly 1.0.0}.`

I've tried several workarounds, including using [jetifier](https://github.com/mikehardy/jetifier), but I think this fix will be a bit more involved than changing some paths to support libraries. Specifically, I run into issues migrating `MediaStyle` and `VolumeProviderCompat`. I'm still a novice when it comes to native Android so maybe someone with more Android experience can lend a hand.

1. Sample code (provide repo url or sample code)

https://github.com/timmywil/react-native-music-control-example

This project was created with `react-native init` and then react-native-music-control added with `yarn add react-native-music-control`. Note that RN 0.60 has autolinking, so `react-native link` should not be used.

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by ouabing** [comment]
Add following line to `node_modules/react-native-music-control/android/build.gradle`

```
implementation 'androidx.core:core:1.0.2'
```

**Comment by timmywil** [comment]
@ouabing set me on the right path, but everything needed to be moved over to androidx to compile.

**Comment by ouabing** [comment]
@timmywil Using [jetifier](https://github.com/mikehardy/jetifier) and adding a postinstall script to your `package.json` will allow you to transfer non-AndroidX projects to AndroidX compatible temporally.

**Comment by timmywil** [comment]
@ouabing That did not work for this project.

**Comment by timmywil** [comment]
I noticed in https://github.com/react-native-community/react-native-slider they now publish a `next` tag on npm for RN 0.60. That might be a good solution here as well.

**Comment by schumannd** [comment]
Does this package support RN +0.60, autolinking, androidx etc.?

**Comment by tanguyantoine** [comment]
No work has been down on this side. Do you have sone link we can refer to so that we can do the necessary to make it work? Can you help in that sense?

**Comment by schumannd** [comment]
@tanguyantoine 

Unfortunately I have no such experience either. But with a quick search I found [this readme](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) which seems detailed enough.

**Comment by timmywil** [comment]
This package already works for me with RN 0.60+. This is the PR that did the necessary migration to androidx. The only thing necessary for iOS was to have a podspec, which this package has.

**Comment by timmywil** [comment]
In fact, I don't think this package would work with <=0.59 anymore unless you did a reverse [jetify](https://github.com/mikehardy/jetifier).

**Comment by The0racle** [comment]
@timmywil Is it possible to reverse Jetify? It seems this package is using Android X exclusive libs. See #342
