### ISSUE TITLE
 MusicControl.on('pause', ...) doesn't get called when there is a phone call

### ISSUE THREAD

**Issue by gazedash** [tanguyantoine/react-native-music-control#283]
onAudioFocusChange on android doesn't get called when there is an icnoming call. It works when there are headphones connected. You will see if you add a log to `react-native-music-control/android/src/main/java/com/tanguyantoine/react/MusicControlAudioFocusListener.java` line 26

2. Platform ?

   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [ ] Simulator
  - [X] Real device

**Comment by jeanffc** [comment]
I have the same problem :/

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
