### ISSUE TITLE
Unwanted app icon fallback for artwork on iOS

### ISSUE THREAD

**Issue by karaoak** [tanguyantoine/react-native-music-control#285]
# Description
When calling: 
```
MusicControl.setNowPlaying({
    artist,
    title,
    artwork,
)
```
with either a locally required image or remote image url that's not different from the currently displayed artwork image, there will always be a fallback to the app icon of the app.

I would expect when the artwork image does not change, you will not notice any update or flicker in the display of this image on the lockscreen of your iOS device.

Now e.g. image1.png is shown, you call setNowPlaying({artwork: 'image1.png'}), and you will first see the image on the lockscreen update to the appicon and then see it change back to image1 again.

Is this how iOS works? Or can this be changed in your library.
Thank you for any info on this matter.

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [] Simulator
  - [x] Real device

**Comment by RWOverdijk** [comment]
@karaoak I think I'm seeing similar behaviour, but for me it's only loading the image once. If I replay the same item, it shows the app icon. The only way to get back the cover is by changing the url.

Did you manage to solve this?

**Comment by marf** [comment]
I have the same problem!
