### ISSUE TITLE
Android pause from notification recreates notification

### ISSUE THREAD

**Issue by jarredwitt** [tanguyantoine/react-native-music-control#286]
# Description 

When pressing the pause button on the music control notification in the notification drawer, the notification is destroyed and a new one is created. Pressing play on the new notification plays the audio, but the state of the notification remains and does not switch to show the artwork, title or the pause button that the original had. When playing/pausing from within my app using my controls once the new notification is shown, the state never updates, even if I try to force it use `updatePlayback`. This only happens when using the pause button on either the lock screen or the music control notification. 

Repro steps:
1. Play audio from within App.
2. Go to either the lock screen or the notifications drawer.
3. Press the pause button on the music control notification (should see the original music controls disappear and then come back).
4. Press the play button on the newly created notification (notification should remain the same and not update but audio should play).

I found that commenting out this line of code fixes the issue:
https://github.com/tanguyantoine/react-native-music-control/blob/ecfd084454a5ed8d4cd0fa07da986983cf9b1ddc/android/src/main/java/com/tanguyantoine/react/MusicControlEventEmitter.java#L41

I'm not an Android dev, but why would `stopForegroundService()` need to be called if we are just pausing the audio? Seems like that should be in the `onStop` event. Just speculating and could be completely wrong. 

Can submit a PR if it needs to be moved.

2. Platform ?

   - [ ] iOS
   - [x] Android
   
3. Device
  - [x] Simulator
  - [ ] Real device

**Comment by rborn** [comment]
@jarredwitt I have the same, did you test with the change you are suggesting? Thnx

**Comment by rborn** [comment]
@jarredwitt I tested directly in node_modules and it works, I commented that line. So if you want please make the PR ❤️

**Comment by t2** [comment]
@rborn @jarredwitt I don't get a new notification but the controls don't work at all. Can you share your code where you enable the controls?

**Comment by rborn** [comment]
I'm just using the code as specified in readme.

**Comment by t2** [comment]
@rborn You just copied the exact Basic Controls section? You mind pasting the code you're using for your enabling of controls?

**Comment by rborn** [comment]
mine is something like this:
~~~
import MusicControl from 'react-native-music-control';

//...

 constructor(props) {
        super(props);

        MusicControl.enableBackgroundMode(true);
        MusicControl.enableControl('play', true);
        MusicControl.enableControl('stop', false);
        MusicControl.enableControl('pause', true);

        MusicControl.enableControl('togglePlayPause', true);
        MusicControl.enableControl('skipForward', true, { interval: SEEK_TIME });
        MusicControl.enableControl('skipBackward', true, { interval: SEEK_TIME });

        MusicControl.handleAudioInterruptions(true);

        MusicControl.on('play', () => {
            this.paused = false;
        });

        MusicControl.on('pause', () => {
            this.paused = true;
        });

        MusicControl.on('stop', () => {
            this.paused = true;
        });

        MusicControl.on('skipForward', () => {
            this.onSkip(SEEK_TIME);
        });
        MusicControl.on('skipBackward', () => {
            this.onSkip(-SEEK_TIME);
        });

        MusicControl.on('togglePlayPause', () => {
            this.paused = !this.paused;
        });

//...


componentWillUnmount() {
	MusicControl.stopControl();
}

//...

onMediaLoad = () => {
	this.setMusicControl();
};

setMusicControl = () => {
	MusicControl.setNowPlaying({
		title: appStore.currentPlaying.session.name,
		artwork: images.defaultArtwork,
		artist: 'Emjoy',
		duration: this.duration
	});
};
~~~

Keep in mind that I have removed code (non essential) , I use MobX for state management and I applied the fix https://github.com/tanguyantoine/react-native-music-control/issues/286#issuecomment-519205397 directly in node_modules

and  "react-native-music-control": "0.10.4",

**Comment by rborn** [comment]
@jarredwitt do you mind making the PR, maybe we get it merged? 🤗

**Comment by rborn** [comment]
@tanguyantoine ❤️

**Comment by tanguyantoine** [comment]
published under `0.10.7`

**Comment by t2** [comment]
@rborn @jarredwitt Thanks, guys! Getting closer but it's still not working exactly as expected. The pause works but the play button never shows, I cannot swipe the notification away, and the lock screen shows the next track icons instead of the skip forward and back. Any thoughts there?

**Comment by t2** [comment]
@jarredwitt @rborn Got it all working as expected on the notifications. I will tackle lock screen next. Thank you both for your help!
