### ISSUE TITLE
Version 0.10.5 introduces notification errors on android

### ISSUE THREAD

**Issue by rborn** [tanguyantoine/react-native-music-control#288]
# Description

With version 0.10.5 on Android the controls on the notification won't work correctly anymore.
After you pause the media from the notification controls the notification will recreate and move to pause state but lose the artwork and also won't switch back to play mode -  the buttons won't update (however the audio does start to play)

- Android 9
- Nokia 7 Plus

1. Sample code (provide repo url or sample code)

Just updated the module from `0.10.4`

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?
