### ISSUE TITLE
When audio start playing. Notification will dismiss.

### ISSUE THREAD

**Issue by SwiftyWang** [tanguyantoine/react-native-music-control#296]
# Description
Using XIAOMI 8 to debug.
After audio start to play, the notification will disappear.
btw: I using this lib to display notification and use **_react-native-video_** to play music.
1. Sample code (provide repo url or sample code)
After debug the Android code of this lib. I find 
```
public void onStop() {
        stopForegroundService();
        sendEvent(context, "stop", null);
}
```
is been called.

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by vjhameed** [comment]
I am also facing this
