### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by RWOverdijk** [tanguyantoine/react-native-music-control#298]
@tanguyantoine are you still on this project? I see a lot of valid issues without a response. Do you need help?

**Comment by tanguyantoine** [comment]
Help is very welcomed :-)

**Comment by tanguyantoine** [comment]
I'm not an Android expert and not really investing time in iOS either. Who ever wants to contributes is welcome.

**Comment by RWOverdijk** [comment]
@tanguyantoine I get that. I'll maintain a fork for now, I'll actively be using this somewhere this week and start fixing things when needed.
