### ISSUE TITLE
NowPlayingPlaybackState not working on iOS 13

### ISSUE THREAD

**Issue by sfreeman28** [tanguyantoine/react-native-music-control#299]
# Description

Updated to Xcode 11 to test on a simulator running iOS 13.
Now when changing the playback state using `MusicControl.updatePlayback` it does not update the state in the NowPlaying notification correctly.
Eg: if notification is in Paused state and set to MusicControl.STATE_PLAYING, the notification remains Paused.
Note when clicking actions on the notification itself the state is correct, I'm just having issues with setting state from my app.

Tested on a simulator running iOS 12 and is working as expected.

1. Sample code (provide repo url or sample code)

Just call `MusicControl.updatePlayback` on iOS 13 device.

2. Platform
   - [x] iOS
   - [ ] Android
   
3. Device
  - [x] Simulator
  - [x] Real device

Has anyone else noticed this issue? Its working fine for me on iOS12 but not iOS13.

Thanks

**Comment by tanguyantoine** [comment]
Do you experience the same result with a real device?

**Comment by dylancompanjen** [comment]
I'm having issues on my iOS app aswel since I updated to iOS13.

**Comment by sfreeman28** [comment]
> Do you experience the same result with a real device?

Yes a client first witnessed the issues on their real device.

**Comment by BloodyBeans** [comment]
I'm also having issues since i upgraded to iOS 13. 
For example:
 - Instead of previous and next icons the icons for 10 seconds forward and 10 seconds backwards appear
- The music controls disappear when the application goes to background
- Song information does not appear sometimes

**Comment by gonchar** [comment]
iOS 13 API has been changed, requires small fix

**Comment by JustinKasad** [comment]
I am also having this problem.  Music controls and now playing metadata are not being set on ios 13.   There are no errors in the logs.  

@dylancompanjen @sfreeman28 were you able to find a workaround?

**Comment by sfreeman28** [comment]
> @dylancompanjen @sfreeman28 were you able to find a workaround?

No I haven't. The metadata seemed to show up for me, but it was the playing/paused state that was not working correctly.

**Comment by dylancompanjen** [comment]
@sfreeman28 no, I'm also getting reports now that the background controls won't show up anymore in a lot of cases.

**Comment by parthya** [comment]
Is this resolved? 

> While the state is MusicControl.STATE_PLAYING it will show the pause icon, and while the state is MusicControl.STATE_PAUSED it will show the play icon.

The audio is paused but the icon doesn't change to play icon.
