### ISSUE TITLE
Auto-destroy?

### ISSUE THREAD

**Issue by jasongrishkoff** [tanguyantoine/react-native-music-control#30]
Last night before I went to sleep I paused my music app from the notification.  This morning, when I woke up, it was still there.  I tried interacting with the buttons, but they aren't doing anything.  I plugged into to my Android Device Monitor to check the logs, and clicking the media control buttons (play, skip to next) does absolutely nothing in the logs.

I'm guessing this is because the main activity React Native app has been completely destroyed from the phone's memory, but the notification persists?  Perhaps the solution is to automatically destroy the notification after X hours of inactivity?

**Comment by Guichaguri** [comment]
The service that this package creates is exactly for that, when the app is terminated in any form, the notification is destroyed.

I don't know why it didn't work. Can you check the services if it happens another time?

**Comment by jasongrishkoff** [comment]
I wonder if it has something to do with doze mode?  I do note that if I'm actively using the phone and close the app, the notification is destroyed.  But if I've got the app running in the background flipping through a playlist, pause it, and go to sleep -- when I wake up, the notification is still there, but it's as if Android has done away with the app?  Because the notification becomes pretty useless :(

**Comment by Guichaguri** [comment]
A possible solution would be launching the app, and then triggering the event. How about that?

**Comment by Guichaguri** [comment]
Does this problem still happens?

**Comment by jasongrishkoff** [comment]
I think it's related to #45
