### ISSUE TITLE
Feature: close notification

### ISSUE THREAD

**Issue by mayconbenito** [tanguyantoine/react-native-music-control#300]
### Description
When calling `MusicControl.resetNowPlaying() or MusicControl.stopControl()` the notification continues to show like that:
![oie_EXuKU4axf2aK](https://user-images.githubusercontent.com/28637562/67628508-6c01cd00-f845-11e9-9588-77a0ccf063c9.png)

It would be nice to have a function to close the notification like: `MusicControl.closeNotification()`

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by mayconbenito** [comment]
Just tried and the same thing is happening on 0.10.8
