### ISSUE TITLE
null is not an object (evaluating 'NativeMusicControl.STATE_PLAYING') - Ejected Expo (ExpoKit) 35.0.0

### ISSUE THREAD

**Issue by pedro-lb** [tanguyantoine/react-native-music-control#303]
![image](https://user-images.githubusercontent.com/22061051/68340100-9153ce00-00c4-11ea-954f-a2d5b3ae45f6.png)

# Description

When using this lib with `Expo` (SDK 35.0.0, ejected using `ExpoKit`), I get this error above just by doing `import MusicControl from 'react-native-music-control';`.

I've tried the following below. Nothing works.
* Linking with `react-native link react-native-music-control`;
* Manual linking;
* Not linking at all (using `Jetifier`).

1. Steps to reproduce
* `expo init <project-name>` (with version 35.0.0)
* `expo eject` (using ExpoKit)
* `yarn add react-native-music-control`
* `react-native link react-native-music-control`
* Add permissions to `AndroidManifest.xml
* Add `import MusicControl from 'react-native-music-control';` to any file (e.g. `HomeScreen.js`)
* `expo start`
* error happens :(

2. Platform ?
   - [ ] iOS
   - [X] Android
     
3. Device
  - [X] Simulator
  - [X] Real device

4. Related issues
* https://github.com/expo/expo/issues/6188
* https://github.com/tanguyantoine/react-native-music-control/issues/112
* https://github.com/tanguyantoine/react-native-music-control/issues/167
* https://github.com/tanguyantoine/react-native-music-control/issues/156
* https://github.com/tanguyantoine/react-native-music-control/issues/13

I've also created a repo simulating the issue:
https://github.com/pedro-lb/expo-35-react-native-music-control/

**Comment by pedro-lb** [comment]
Any news here?

@tanguyantoine can you help?

**Comment by tanguyantoine** [comment]
have you tried upgrading the package? I have no expertise in android

**Comment by tanguyantoine** [comment]
can you try this: https://github.com/software-mansion/react-native-gesture-handler/issues/676

**Comment by pedro-lb** [comment]
Thanks @tanguyantoine! I've tried both solutions but neither work. This leads me to think that this in an Expo problem rather than a problem with this lib, since it works flawlessly in normal React Native.

**Comment by tanguyantoine** [comment]
clsing then :-)
