### ISSUE TITLE
Refresh The App and Allow user to close notification

### ISSUE THREAD

**Issue by ajoykarmakar459** [tanguyantoine/react-native-music-control#304]
Thank you for creating this awesome plugin but I am facing some issues,-

1. like when I tap on a play button it's started to show on the notification bar and now if I minimize the app click on the control notification then it refreshes the whole app and plays the music in the background and I lost my player and playing the position. 

2.`MusicControl.enableControl('closeNotification', true, {when: 'paused'})`
I have config the plugins in this way but If I have paused the songs still not able to close the notification on swipe. Sometimes it's working sometimes it's not. My react-native version is 0.61.4 so I don't have to manually link but for unstable work of the plugins makes me confused about what it will do with the customers. Should I configure the plugin with the manual procedure? or something I am missing does?

If anyone gives support it will be really helpful.
Thank you.

**Comment by zatloeri** [comment]
I am facing the same problem with **1.**

What is the right solution for handling the **app refresh on notification press**?
What I would expect it to do is just maximize the minimized app since it can't play if it is not running.
