### ISSUE TITLE
iOS - controls disappear from lockscreen and play / pause from lockscreen not reflects in app

### ISSUE THREAD

**Issue by Pravin-L** [tanguyantoine/react-native-music-control#310]
# Description

1. Sample code (provide repo url or sample code)
  componentDidMount() {
    MusicControl.enableBackgroundMode(true);
    MusicControl.handleAudioInterruptions(true);
    MusicControl.enableControl('play', true);
    MusicControl.enableControl('pause', true);
    MusicControl.enableControl('stop', false);
    MusicControl.enableControl('nextTrack', false);
    MusicControl.enableControl('previousTrack', false);
    MusicControl.enableControl('seekForward', false);
    MusicControl.enableControl('seekBackward', false);
    MusicControl.enableControl('changePlaybackPosition', true)
    MusicControl.on('play', () => {
      this.onPlay();
      MusicControl.resetNowPlaying();
    });
    MusicControl.on("pause", () => {
      this.onPause();
    });
    MusicControl.enableControl('skipForward', false)
    MusicControl.enableControl('skipBackward', false)
    MusicControl.enableControl('enableLanguageOption', false)
    MusicControl.enableControl('disableLanguageOption', false)
    MusicControl.updatePlayback({
      state: MusicControl.STATE_PLAYING, // (STATE_ERROR, STATE_STOPPED, STATE_PLAYING, STATE_PAUSED, STATE_BUFFERING)
      elapsedTime: this.state.currentTime, // Elapsed Seconds (Double)
    })
  }

2. Platform ?

   - [✓] iOS
   
   
3. Device
  - [x] Simulator
  - [ ✓ ] Real device

**Comment by danielle-Cman** [comment]
You could follow: [https://github.com/tanguyantoine/react-native-music-control/issues/301#issuecomment-567341784](url)

**Comment by Pravin-L** [comment]
Thank you @danielle-Cman for your comment, I will check and confirm.

**Comment by Pravin-L** [comment]
It's not working...:(

**Comment by danielle-Cman** [comment]
hmmmm...It really weird.
my side it work well.
Could you send your demo project, I will investigate it.

**Comment by Pravin-L** [comment]
@danielle-Cman, It shows in the notification bar but when I locked my screen it will show without progressing progress bar. And when I unlocked the iPhone It will disappear from the notification bar as well.

Could you please share your mail id?

**Comment by danielle-Cman** [comment]
With on my app:
[https://imgur.com/nbB67RK](url)
my email: iu.developer232@yahoo.com

**Comment by Pravin-L** [comment]
Hello @danielle-Cman,
Where did I get pause and play event, when I did it from notification pause /play?

**Comment by jandog8990** [comment]
Was this issue ever solved? I'm having the exact same issue, but within the iOS simulator.

**Comment by tanguyantoine** [comment]
It has always been buggy in simulator

**Comment by Pravin-L** [comment]
Yes, I am using react-native 0.58 yes the issue remains the same.

**Comment by jandog8990** [comment]
Can you all please update your documentation to let developers know it is buggy, I spent a lot of time trying to fix this "bug" when it would have been helpful to know it's a dead end. It will save people time.

Thanks,

**Comment by tanguyantoine** [comment]
@jandog8990 who are you talking to?

**Comment by jandog8990** [comment]
to you @tanguyantoine you're the maintainer correct?

**Comment by danielle-Cman** [comment]
@Pravin-L Sorry my late.
You need implement this feature: 
```
MusicControl.on('play', () => {
      this.setPause(false);
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PLAYING,
      });
    });
    MusicControl.on('pause', () => {
      this.setPause(true);
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PAUSED,
      });
    });
setPause(value) {
    this.setState({paused: value});
    if (value)
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PAUSED,
      })
    else {
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PLAYING,
      })
    }
  }
....
<Video
          ...
          paused={this.state.paused}
          ...
/>
```

**Comment by tanguyantoine** [comment]
@jandog8990 you are more than welcome to open a pull request. Keep in mind that OSS rely on community and rely on contribution. Feel free not to use this package of it does not fit your needs.
