### ISSUE TITLE
App crash :  MusicControl.enableControl('pause', true)

### ISSUE THREAD

**Issue by longman6** [tanguyantoine/react-native-music-control#314]
# Description
  This code caused the following error. 
 ```javascript
  MusicControl.enableControl('pause', true)
```
or 
```javascript
  MusicControl.enableControl('pause', true)
```
   java.lang.IllegalArgumentException: setShowActionsInCompactView: action 0 out of bounds (max -1)

1. Sample code (provide repo url or sample code)
```javascript
play(){
    this.whoosh.play((success) => {
      if (success) {
      } else {
        console.log('playback failed due to audio decoding errors');
      }
    });

    MusicControl.setNowPlaying({
      state: MusicControl.STATE_PLAYING, 
      title: 'Billie Jean',
      artwork: 'https://i.imgur.com/e1cpwdo.png',
      artist: 'Michael Jackson',
      album: 'Thriller',
      genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
      duration: this.whoosh.getDuration(),
      
    })
    MusicControl.enableControl('play', false)
    MusicControl.enableControl('pause', true)
  
    this.setState({
      play: true
    })
  }
```
2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device
            Samsung SM-J7227S
            Samsung-G950N
4. package 
   "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-music-control": "^0.10.8",
    "react-native-sound": "^0.11.0"

**Comment by Esirei** [comment]
Had this issue too, but updating the state of the MusicControl to STATE_PAUSED while the enableControls's are in the constructor worked for me.

**Comment by tanguyantoine** [comment]
@Esirei would you mind sharing how you achieved that?

**Comment by Esirei** [comment]
> @Esirei would you mind sharing how you achieved that?

`
  constructor() {
    ...
    MusicControl.enableControl('play', true);
    MusicControl.enableControl('pause', true);
    ...
  }

  playFile = file => {
    if (this.sound) {
      this.sound.release();
    }
    this.sound = new Sound(file.path, '', error => {
      this.current = file;
      if (error) {
        return;
      }
      this.play();
      MusicControl.setNowPlaying({
        title: file.name,
        artwork: file.cover,
      });
    });
  };

  play = () => {
    if (this.sound) {
      this.sound.play(success => {
        success && this.next();
      });
      if (this.state !== 'playing') {
        this.state = 'playing';
        MusicControl.updatePlayback({
          state: MusicControl.STATE_PLAYING,
        });
      }
    }
  };

  pause = () => {
    if (this.sound) {
      this.sound.pause();
    }
    this.state = 'paused';
    MusicControl.updatePlayback({
      state: MusicControl.STATE_PAUSED,
    });
  };
 ....
`

Ignore the weird state assignment, the class is not a react component.

**Comment by tanguyantoine** [comment]
@longman6  Would you mind upgrading and try again?

**Comment by kesha-antonov** [comment]
@Esirei thanks! It helped

We should do
 
```
MusicControl.enableControl('play', true)
MusicControl.enableControl('pause', true)
```

And later update state

```
MusicControl.updatePlayback({
      state: MusicControl.STATE_PAUSED,
    })
```
