### ISSUE TITLE
Error occurs even if I try to import the library

### ISSUE THREAD

**Issue by chinmaygokhale** [tanguyantoine/react-native-music-control#317]
I am using a android simulator on windows machine
![Screenshot_1580556398](https://user-images.githubusercontent.com/43947609/73591512-66d3ae80-4515-11ea-98d9-91b1bc0b27c9.png)

**Comment by tanguyantoine** [comment]
are you using expo?
https://github.com/tanguyantoine/react-native-music-control/issues/303

**Comment by chinmaygokhale** [comment]
Yes, I am using expo.

**Comment by tanguyantoine** [comment]
It does not work with Expo. Expo does not allow external libraries without ejecting. Did you?
