### ISSUE TITLE
react-native-music-control 在安卓Q 崩溃问题

### ISSUE THREAD

**Issue by TSmallin** [tanguyantoine/react-native-music-control#320]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?

   - [ ] iOS
   - [-] Android
   
   
3. Device
  - [ ] Simulator
  - [-] Real device

![截屏2020-02-24下午6 28 55](https://user-images.githubusercontent.com/11835325/75145321-ae73e180-5733-11ea-8a70-ca219e701ed7.png)

**Comment by TSmallin** [comment]
![截屏2020-02-24下午6 28 55](https://user-images.githubusercontent.com/11835325/75146180-81c0c980-5735-11ea-909f-afce838cb086.png)

**Comment by tree1891** [comment]
I have same issue.
