### ISSUE TITLE
Adding custom icons

### ISSUE THREAD

**Issue by vjhameed** [tanguyantoine/react-native-music-control#322]
# Description

Hi

Thanks for creating this awesome lib. I love it. But there is a problem with icons they seem to be different across android phones. I would like to know how can i fontawesome or ionicons for the controls so that its the same across all devices.

Thanks in advance

1. Drawable Resoirce

2. Platform ?

   - [ ] iOS
   - [x] Android
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by bradleyflood** [comment]
Thanks @vjhameed I'm pretty sure this is OS specific and not controllable by this module.
