### ISSUE TITLE
Update Github Meta

### ISSUE THREAD

**Issue by bradleyflood** [tanguyantoine/react-native-music-control#326]
@tanguyantoine Can you please update the Github project Meta.

Description:
```
Display and manage media controls on lock screen and notification center for iOS and Android.
```

URL:
[https://www.npmjs.com/package/react-native-music-control](https://www.npmjs.com/package/react-native-music-control)

I'm keen to remove the old "not maintained" message ->

<img width="882" alt="Screen Shot 2020-05-28 at 20 46 01" src="https://user-images.githubusercontent.com/1085976/83132332-93df4900-a124-11ea-81dd-72edf60be26d.png">

**Comment by tanguyantoine** [comment]
done
