### ISSUE TITLE
Add Intent Meta to Readme Installation Guide

### ISSUE THREAD

**Issue by bradleyflood** [tanguyantoine/react-native-music-control#327]
Need to add the Android Intent meta to the README Installation to prevent bugs.

This resolves the bug of multiple app instances when tapping the notification in Android (with app in background.

```
<activity
  android:name=".MainActivity"
  android:launchMode="singleTask">
```

See https://reactnative.dev/docs/linking#enabling-deep-links

**Comment by rborn** [comment]
@bradleyflood for me it works with `singleTop` too.

Btw can this be merged? 😄

**Comment by bradleyflood** [comment]
Hi @rborn sorry for the delay. I've been so busy with my own app - had a big deadline to meet.

I'll get to this soon and let you know. Thank you!

**Comment by bradleyflood** [comment]
Fix to be deployed in https://github.com/tanguyantoine/react-native-music-control/pull/383
