### ISSUE TITLE
Publish NPM Patch Update

### ISSUE THREAD

**Issue by bradleyflood** [tanguyantoine/react-native-music-control#328]
Once #325 is done can you please publish an NPM patch? `v0.11.1`?

Cheers
Brad

**Comment by bubah** [comment]
Hey Bradley, Is this repo being maintained by you? When i looked at this library a few months ago there was a deprecation notice but that is no longer there so i wasn't sure.

**Comment by bradleyflood** [comment]
Hi @bubah yep I'm working on this repo now :) 

I wasn't happy with the alternative (react-native-track-player) and we depend on this module for our app.

Do you use it?

**Comment by rborn** [comment]
@bradleyflood this is so great news 😻, we're also using it and were not happy with react-native-track-player

Let me know how I can help (my java/objC knowledge are close to zero though)

**Comment by bubah** [comment]
@bradleyflood yes we depend on this module for our app as well. Happy to hear this module is being maintained again.

**Comment by bradleyflood** [comment]
Thanks @bubah and @rborn :)
I think the best way you can help is posting any bugs you find or fixes you've implemented.

Thanks :)
Brad
