### ISSUE TITLE
RN-music-control import error.

### ISSUE THREAD

**Issue by Danil-Dorokhin** [tanguyantoine/react-native-music-control#339]
# Description
I initialized my app with expo, and when i imported rn-music-control it throw me this error:
TypeError: null is not an object ( evaluating 'NativeMusicControl.STATE_PLAYING' )
i tried to link it, but it didnt help so i ejected expo and then tried to link it with 'react-native link', when it didnt help i linked it manualy but it didnt work too. 
this is from my react-native info if it can help :

IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_211
    Python: 3.8.4
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1
    react: ~16.11.0 => 16.11.0
    react-native: ~0.62.2 => 0.62.2

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [ x] Real device

**Comment by wassimbrsimo** [comment]
I faced the same issue ,I've managed to fix it using :
`npm install react-native-music-control`
`./gradlew clean`
`react-native run-android`

**Comment by Danil-Dorokhin** [comment]
Thanks, it helped
