### ISSUE TITLE
Notification swipe is not working. And once kill the app audio will to be stopped. It is keep playing. And Other rest of the thing is working perfectly.

### ISSUE THREAD

**Issue by Kalana-Ramesh** [tanguyantoine/react-native-music-control#340]
# Description

1. Sample code (provide repo url or sample code)

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by catmans1** [comment]
@Kalana-Ramesh Could you provide more detail about that issue?

**Comment by Kalana-Ramesh** [comment]
The issue is occurring on Android real device

**Comment by bradleyflood** [comment]
Closing as not enough info to work on.
