### ISSUE TITLE
React Native Music controls does not appear on real iOS device lock screen at all

### ISSUE THREAD

**Issue by krunalbad** [tanguyantoine/react-native-music-control#366]
React Native Music controls does not appear on real iOS device lock screen at all
but appears on iOS simulator but controls does not work at all

but same code works 99% on android
except in android the notification does not go away on reset function

react-native: 0.63.2
react-native-music-control: 1.4.0-alpha
https://www.npmjs.com/package/react-native-music-control/v/1.4.0-alpha

Is there any other setup required for iOS ?

**Comment by krunalbad** [comment]
i have did some workaround for android double notification issue. 
found out the issue was from my code side. in android i works fine. 
but it is still not working at all for ios. 
need assistance for ios. 
how to make it working for ios ? @tanguyantoine

**Comment by iamchrispham** [comment]
lock controls are displaying for me on iOS 14. I've ran into an issue on iOS but not on Android such that if there were multiple instances of some media content, you would want to ensure that the media content you'd want to display within the lock controls isn't being mixed with another media instance. natively the code has issues differentiating what media content takes precedence even if you've set native props for now playing/update playback.

**Comment by DevMMI** [comment]
I'm having this same problem, have also tried earlier versions of this project and can't seem to get anything to show up the IOS lock screen

**Comment by DevMMI** [comment]
Figured out my issue at least, I'm working with react-native-community/audio-toolkit and there's a bug that doesn't let their mixWithOthers flag ever get set to False, you can test this by playing your app audio at the same time as another app's audio. 

If you're audio can play at the same time as another app's audio, then react-native-music-control **will not work**. Merging [this commit](https://github.com/react-native-audio-toolkit/react-native-audio-toolkit/pull/224) into your code should solve the mixWithOthers issue in react-native-audio-toolkit, which should make your lock screen controls from this package work.

**Comment by krunalbad** [comment]
apparently i am using react-native-track-player and react-native-video that's y i am having trouble having controls in ios
and both packages provides options `mixWithOthers` but none gets successful to get `react-native-music-control` started

**Comment by DevMMI** [comment]
@krunalbad do you set mixWithOthers to false on both those packages and react-native-music-controls still doesn't work? Try checking whether those flags are being obeyed, i.e. whether you can play audio at the same time as another app.

**Comment by krunalbad** [comment]
i have tried mixWithOthers in both pkgs [trackplayer](https://react-native-track-player.js.org/documentation/#functions) and [rn-video](https://github.com/react-native-video/react-native-video#mixWithOthers) but none helped

**Comment by krunalbad** [comment]
Closing this issue due to other pkgs conflicts
