### ISSUE TITLE
Does not work on Android 11

### ISSUE THREAD

**Issue by goleary** [tanguyantoine/react-native-music-control#369]
When I run the same application on Android 10 & 11 I see this:

-  Android 10 - works as expected
![image](https://user-images.githubusercontent.com/16123225/103043368-8b6fb500-4531-11eb-8b4b-689c997addff.png)

- Android 11 - persistent "notification" never shows
![image](https://user-images.githubusercontent.com/16123225/103042187-a50efd80-452d-11eb-9094-e2485a5c968c.png)

# Description

1. Sample code (provide repo url or sample code)

https://github.com/goleary/react-native-music-control-min-repro

This is just a new react-native app with `MusicControl` added & enabled.

2. Platform ?

   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device
 
(I tested on both)

**Comment by goleary** [comment]
Turns out I was not calling `MusicControl.setNowPlaying()`

In Android 10 the Music notification shows up even without calling that method (if you just call `MusicControl.enableControl('play', true)`.

On Android 11 if you don't call it then nothing shows up.

Here it is working:
![image](https://user-images.githubusercontent.com/16123225/103179728-b3b62700-4843-11eb-88a2-c20f5e0dc1f2.png)

**Comment by tanguyantoine** [comment]
May I ask you to update the readme ? 🙏

**Comment by goleary** [comment]
Sure! I switch the order of the "Now Playing" & "Enable and Disable controls" sections.

Everything was in the readme, but the ordering of methods in the readme is what tripped me up
