### ISSUE TITLE
Adding screenshots to readme

### ISSUE THREAD

**Issue by tanguyantoine** [tanguyantoine/react-native-music-control#37]
# Description

We need to give a clear/quick overview of what this repository/package is doing. 

We should add screenshots for both platform to readme

- [x] iOS (@tanguyantoine)
- [ ] Android (@Guichaguri)

**Comment by Guichaguri** [comment]
We should use the same data for both devices (same title, artist, artwork, etc). I'll let you choose the track.
We also should leave the code that we used for the screenshots as an example

The Android support also works with other external devices, such as Android TV, Android Auto, Google Cast, Android Wear, and even some other devices that don't use Google software. Unfortunately, those devices will have to stay only as text.

**Comment by tanguyantoine** [comment]
I let you choose the soundtrack :)

**Comment by Guichaguri** [comment]
Let's use the one in the README: Billie Jean by Michael Jackson.

```js
MusicControl.setNowPlaying({
  title: 'Billie Jean',
  artwork: 'http://i.imgur.com/e1cpwdo.png',
  artist: 'Michael Jackson',
  album: 'Thriller',
  genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
  duration: 294,
  description: 'Billie Jean is a song by American singer Michael Jackson. It is the second single from the singer's sixth solo album, Thriller (1982). It was written and composed by Jackson and produced by Jackson and Quincy Jones.',
  color: 0x4d59fc,
  date: '1983-01-02T00:00:00Z',
  rating: 84
})

MusicControl.setPlayback({
  state: MusicControl.STATE_PLAYING,
  speed: 1,
  elapsedTime: 103,
  bufferedTime: 200
})

MusicControl.enableControl('play', true)
MusicControl.enableControl('pause', true)
MusicControl.enableControl('stop', false)
MusicControl.enableControl('nextTrack', true)
MusicControl.enableControl('previousTrack', true)
```

**Comment by cinder92** [comment]
done in android!

**Comment by tanguyantoine** [comment]
@cinder92 can you upload it here ?

FYI, I'm currently trying to create a snapshot but I'm not able to run the app on iOs due to expired membership 😠  Will try asap to upload the picture

**Comment by tanguyantoine** [comment]
I added an image into doc folder , branch : add-screenshot

I will update the readme once we will have both

**Comment by tanguyantoine** [comment]
@Guichaguri are you able to provide a scrrenshot for android ?
btw I updated the demo app : https://github.com/tanguyantoine/react-native-music-control-demo

**Comment by tanguyantoine** [comment]
It would be awesome to have the Android demo version ;-)

**Comment by tanguyantoine** [comment]
up
