### ISSUE TITLE
ios controls persist after calling `MusicControl.stopControl`

### ISSUE THREAD

**Issue by PupoSDC** [tanguyantoine/react-native-music-control#376]
# Description

I'm calling `MusicControl.stopControl()` on the clean up fuction of `useEffect`:

```tsx

 useEffect(() => () => {
   MusicControl.stopControl();
 });
```

but the player persists after this call.

Before the callback:

![image](https://user-images.githubusercontent.com/9625304/109654455-7f702700-7b62-11eb-902c-e32cba250e8b.png)

after the callback:

![image](https://user-images.githubusercontent.com/9625304/109654524-9151ca00-7b62-11eb-96f5-2ff1dd9be877.png)

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [ ] Real device

**Comment by PupoSDC** [comment]
I dug quite bit into the code and

```objective-c
RCT_EXPORT_METHOD(resetNowPlaying)
{
    MPNowPlayingInfoCenter *center = [MPNowPlayingInfoCenter defaultCenter];
    center.nowPlayingInfo = nil;
    self.artworkUrl = nil;
}
``

appears to be working as intended. `center.nowPlayingInfo = nil`  is set correctly, which according to the docs should be sufficient to make the controls disappear:

https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter/1615903-nowplayinginfo

**Comment by PupoSDC** [comment]
So in the end the answer was hidden in a somewhat cryptic post from 2018:

https://github.com/tanguyantoine/react-native-music-control/issues/135#issuecomment-396554383

You have to change the state of the controls to `STOPPED` before closing the controls, otherwise they will not close!

```tsx
      MusicControl.updatePlayback({
        state: MusicControl.STATE_STOPPED,
        elapsedTime: 0,
      });
      MusicControl.stopControl();
```

**Comment by leightonkuchel** [comment]
Hmm even when setting it's state (literally copy/paste yours) I can't get it to hide the controls 🤔

**Comment by bradleyflood** [comment]
@leightonkuchel How did you go with this? Is this an iOS issue? or related to our package here?

**Comment by AliHaidar110** [comment]
> So in the end the answer was hidden in a somewhat cryptic post from 2018:
> 
> [#135 (comment)](https://github.com/tanguyantoine/react-native-music-control/issues/135#issuecomment-396554383)
> 
> You have to change the state of the controls to `STOPPED` before closing the controls, otherwise they will not close!
> 
> ```tsx
>       MusicControl.updatePlayback({
>         state: MusicControl.STATE_STOPPED,
>         elapsedTime: 0,
>       });
>       MusicControl.stopControl();
> ```

didn't work :(
