### ISSUE TITLE
Calling Music.stopControl() on Android before setNowPlaying causes null reference crash

### ISSUE THREAD

**Issue by goleary** [tanguyantoine/react-native-music-control#380]
```
Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
```
# Description

1. Sample code (provide repo url or sample code)

Will try to provide a minimal repro later.

2. Platform ?

   - [ ] iOS
   - [x] Android (api 29)
   
   
3. Device
  - [x] Simulator
  - [ ] Real device

**Comment by PupoSDC** [comment]
Is it possible you are calling `MusicControl.handleAudioInterruptions(true);`? This call only works on ios and causes a crash in android.

**Comment by goleary** [comment]
We are not using that method, thanks for the tip though!

**Comment by PupoSDC** [comment]
Maybe you can share your setup? 

The README says:

```
Make sure when you call MusicControl.resetNowPlaying() and MusicControl.stopControl() you must have controls enabled otherwise it will create issues
```

So doing what you describe in the title isn't exactly recommended. But i personally have not had issues with this so far.

**Comment by goleary** [comment]
Interesting, I never noticed that. I'm going to go ahead and close this because I don't have time to dig in further at the moment & because this is called out in the readme.
