### ISSUE TITLE
[Android] Customizing notification icons in compact view

### ISSUE THREAD

**Issue by armaanshah96** [tanguyantoine/react-native-music-control#384]
# Description
Hi,

I noticed that a PR was recently merged to add ACTION_FAST_FORWARD and ACTION_REWIND to the compact notification screen on Android which is great! On my current project I'd like to go one step further and be able to customize which notification icons of the ones enabled I'd like to present in the compact view.

I currently `enableControl` for:
- play
- pause
- stop
- skipForward
- skipBackward

In the full expanded view, I see what I expect, which is (in order):
- skipBackward
- play or pause
- stop
- skipForward
 
However in the compact view, I see:
- skipBackward
- play or pause
- stop

I believe this is because Android limits the number of controls available in the compact view to 3 (based on the [docs](https://developer.android.com/reference/androidx/media/app/NotificationCompat.MediaStyle#setShowActionsInCompactView(int...)) I've seen at least). I would like to replace "stop" with "skipForward" in the compact view.

Goal: I want to specify which 3 controls are visible in compact view

Proposal: Adding functionality on `enableControl` to take a new options key `compactView` with a boolean value. This boolean would be used to collect which actions should be enabled in compact view when running `setShowActionsInCompactView` in `MusicControlModule` in Android. Alternatively, a custom function like `setCompactViewActions` that takes a list of actions might work as well.

I'm new to this library, so might be missing some considerations (or if this is possible already I may have just missed it ). Thoughts on this feature?

Platform ?
   - [ ] iOS
   - [x] Android

**Comment by bradleyflood** [comment]
Sounds good @armaanshah96 :)

**Comment by bradleyflood** [comment]
On @armaanshah96 's todo list :)

**Comment by armaanshah96** [comment]
yup noted, apologies, been struggling to find time recently

**Comment by bradleyflood** [comment]
You and me both haha :)
