### ISSUE TITLE
Not working on iOS with react-native-audio-toolkit framework

### ISSUE THREAD

**Issue by futureinapps** [tanguyantoine/react-native-music-control#392]
# Description

1. Sample code (provide repo url or sample code)

in `componentDidMount` i call this:

```
RNMS.enableBackgroundMode(true);
RNMS.handleAudioInterruptions(true);
RNMS.enableControl('play', true);
RNMS.enableControl('pause', false);
RNMS.enableControl('nextTrack', false);
RNMS.enableControl('previousTrack', false);
RNMS.on(Command.play, () => {
  dispatch(startPractice() as any);
});
RNMS.on(Command.pause, () => {
  dispatch(pausePractice() as any);
});
```

onPlay i call `setNowPlaying`

2. Platform ?

   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by bradleyflood** [comment]
Hi @futureinapps, I'm happy to look into this but you'll need to provide a reproducible project or bigger code sample. I need to be able to simulate your issue, but I can't with the above info. Thanks :)

**Comment by futureinapps** [comment]
Yesterday, I spent the tones of time to investigate this issue and found out that it was a bug with the @react-native-community/audio-toolkit framework. I solved the problem by adding [this](https://github.com/react-native-audio-toolkit/react-native-audio-toolkit/pull/224/files) changes

**Comment by bradleyflood** [comment]
Ok sweet thanks @futureinapps
