### ISSUE TITLE
Pause does not strop duration

### ISSUE THREAD

**Issue by deshiknaves** [tanguyantoine/react-native-music-control#40]
On RN 41. Everything works as expected. Except when I pause the audio, the duration doesn't pause - it keeps going one. Is there a way to manually pause the duration on iOS?

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [X ] iOS
   - [ ] Android
   
   
3. Device
  - [X ] Simulator
  - [ ] Real device

**Comment by deshiknaves** [comment]
Looked thought the source code and there is nothing currently in there to achieve this. I'll send through a pull request that will allow this.

**Comment by tanguyantoine** [comment]
closed by #41
