### ISSUE TITLE
Please create new Version (1.4.1) and release on npm

### ISSUE THREAD

**Issue by rafaelmaeuer** [tanguyantoine/react-native-music-control#401]
# Description

Please release a new version of this lib on npm which includes the latest PR with fix for Android 12: 
- https://github.com/tanguyantoine/react-native-music-control/pull/397

At the moment usage of patch-package or git as npm-source are required...

3. Platform ?

   - [x] iOS
   - [x] Android
   
   
4. Device
  - [x] Simulator
  - [x] Real device

**Comment by bradleyflood** [comment]
Done https://www.npmjs.com/package/react-native-music-control
