### ISSUE TITLE
Does not show pause icon

### ISSUE THREAD

**Issue by jman48** [tanguyantoine/react-native-music-control#42]
# Description
When using music-control I can not get it to show the pause icon. It will show the play icon but when pressed it will not convert/ change into a pause icon (even though the pause and play events are fired correctly).

I tried enabling/ disabling the pause and play controls with MusicControle.enableControl but it still will not show. Even if I just enable the pause control and nothing else it will not show in the notification.

Am I missing something?

1. Sample code (provide repo url or sample code)
https://github.com/jman48/react-native-music-control-demo - Modified for android from the demo provided

2. Platform ?
   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [X] Simulator - Android 6.0 & 7.0
  - [X] Real device - Android 5.0

Thanks

**Comment by Guichaguri** [comment]
There's a `setPlayback` function for Android, you have to set the state to paused.

**Comment by jman48** [comment]
That works perfect thanks

**Comment by darbaoui** [comment]
@jman48 
please can you share the code for using function **setPlayback** to toggle button in notification (Android)
i have the same issue

**Comment by jman48** [comment]
@darbaoui Use updatePlayback function like so:

To set play icon
```
MusicControl.updatePlayback({
  state: MusicControl.STATE_PLAYING
})
```
 or to set pause icon
```
MusicControl.updatePlayback({
  state: MusicControl.STATE_PAUSED
})
```
