### ISSUE TITLE
Support local image for artwork

### ISSUE THREAD

**Issue by tanguyantoine** [tanguyantoine/react-native-music-control#46]
# Description

Expected api call : `MusicControl.setNowPlaying({ artwork: require('../images/album.png') }); `

same as #44 and #43  but for iOs 

1. Platform ?
   - [x] iOS

**Comment by Guichaguri** [comment]
I'll leave here some information which might help you for iOS support for this.

First of all, you need to resolve the require, RN has a function for this which is located at `react-native/Libraries/Image/resolveAssetSource`. [Here](https://github.com/tanguyantoine/react-native-music-control/blob/master/index.android.js#L34-L36) is the JS code used in the Android side, you might want to copy it to the iOS index.

After you passed the result to the native function, you need to check the type of the "artwork" property:
If it's a map, you can assume it's local and the URI is located in the `uri` property (string) of the map.
If it's a string, you can assume it's remote and the URL is the string.

At least for Android, RN has a helper method for loading local image URIs. If you don't find anything, you can load them the way you used to load local images before.

**Comment by SteffeyDev** [comment]
It appears that the android fix would work on iOS as well, because using 

`MusicControl.setNowPlaying({artwork: resolveAssetSource(require('path/to/image.png')).uri});`

fixed it for me on iOS.

**Comment by Guichaguri** [comment]
@SteffeyDev It works but it's not the proper solution to this problem. Currently, the iOS side detects when the artwork starts with "http", if it does, it loads a remove artwork, if not, it loads a local one.
In Android, it always loads strings as remote artworks and `require` objects as local artworks. This is better because we can have remote URLs with other protocols, such as ftp.

**Comment by SteffeyDev** [comment]
I am only guessing here, but you could just pass the result of resolveAssetSource || the string to the native code like in index.android.js, then in objective c test if you get a dictionary object.  If yes, use the dictionary["uri"], otherwise load the string as remote.

**Comment by tanguyantoine** [comment]
> MusicControl.setNowPlaying({artwork: resolveAssetSource(require('path/to/image.png')).uri});

Does that work to display local image ? would be pretty straight forward to make it work on iOs this way :)

**Comment by SteffeyDev** [comment]
That would certainly work, but for consistancy between iOS and Android you should just do in index.ios.js what you did in index.android.js, and then modify the iOS native module to do the detection and switching. I'll be working on the android native code to figure out why it's not working, so I can test this out as well and throw in a pull request if it works.

**Comment by SteffeyDev** [comment]
@tanguyantoine  This support was added in #78, so this issue can probably be closed now
