### ISSUE TITLE
undefined function updatePlayback

### ISSUE THREAD

**Issue by jasongrishkoff** [tanguyantoine/react-native-music-control#48]
# Description
Just updated to the new code and switched my setPlayback functions to updatePlayback, only to be met with the following.

`Alert
TypeError: undefined is not a function (evaluating '_reactNativeMusicControl2.default.updatePlayback({state:_reactNativeMusicControl2.default.STATE_PLAYING,elapsedTime:100})')`

1. Sample code (provide repo url or sample code)

```
MusicControl.updatePlayback({
  state:MusicControl.STATE_PLAYING,
  elapsedTime:100
})
```

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by Guichaguri** [comment]
I've just tested and it works fine for me. Can you try to reinstall the package?

**Comment by jasongrishkoff** [comment]
100% clean install of package results in the attached.
![screenshot_1488950210](https://cloud.githubusercontent.com/assets/375379/23691121/437793dc-03cf-11e7-9185-24430b930454.png)
![screenshot_1488950200](https://cloud.githubusercontent.com/assets/375379/23691122/4378423c-03cf-11e7-9d7d-ed08e933b42d.png)

**Comment by tanguyantoine** [comment]
I bumped the new version. would you mind upgrade and retry  ?

**Comment by jasongrishkoff** [comment]
Yup, that resolved.
