### ISSUE TITLE
Cannot get lockscreen play control to show up

### ISSUE THREAD

**Issue by natashache** [tanguyantoine/react-native-music-control#50]
# Description
Not sure which part I'm not getting about this library. I followed the demo project, but couldn't get any music control to show up on the lock screen.

Here's some of the code. I'm using react-native-sound. The actual playing/pausing are fired by `this.props.resumePlaying` and `this.props.pauseSession`, which are not included below.

```
import MusicControl from 'react-native-music-control'

class _Player extends Component {
  constructor() {
    super()
    this.state = {
      playSpeed: '1',
      teacher_img: '',
      course_img: ''
    }
    this.playSection = this.playSection.bind(this)
    this.pauseSection = this.pauseSection.bind(this)
  }

  componentDidMount() {
    MusicControl.enableBackgroundMode(true)
    MusicControl.on('play', this.playSection)
    MusicControl.on('pause', this.pauseSection)

    interval = setInterval(this.getProgress.bind(this), 1000)
    this.setState({
      teacher_img: RNFetchBlob.fs.dirs.DocumentDir + '/images/' + this.props.currentCourse.id + '/teacher_img.png',
      course_img: RNFetchBlob.fs.dirs.DocumentDir + '/images/' + this.props.currentCourse.id + '/course_img.png'
    })
  }

  playSection() {
    const section = this.props.sectionPlaying
    const sectionArray = this.props.currentPlayList
    interval = setInterval(this.getProgress.bind(this), 1000)
    this.props.resumePlaying(sectionArray[0], sectionArray)

    MusicControl.setNowPlaying({
      title: section.title,
      artwork: this.state.course_img,
      artist: this.props.currentCourse.teacher,
      album: this.props.currentCourse.name,
      duration: this.props.duration
    })
    MusicControl.enableControl('play', false)
    MusicControl.enableControl('pause', true)
  }

  pauseSection() {
    const section = this.props.sectionPlaying
    clearInterval(interval)
    this.props.pauseSession(section)
    MusicControl.enableControl('play', false)
    MusicControl.enableControl('pause', true)
  }

\\ and then in the render function...

    if(this.props.playing[section.section_id] === true) {
      return (
        <Button transparent onPress={ this.pauseSection }
          style={{ marginLeft: 5, marginRight: 5 }}>
          <Icon name='ios-pause'
            style={{ fontSize: 50, color: '#FFA000' }}/>
        </Button>
      )
    } else if(this.props.paused[section.section_id] === true || this.props.completed[section.section_id] === true) {
      return (
        <Button transparent onPress={ this.playSection }
          style={{ marginLeft: 5, marginRight: 5 }}>
          <Icon name='ios-play'
            style={{ fontSize: 50, color: '#FFA000' }}/>
        </Button>
      )
    }
```
The player itself, handled by react-native-sound, is working fine. But I don't see anything on lockscreen. And I don't see any error or warning either.

Platform: iOS
Device: Real device

**Comment by tanguyantoine** [comment]
would you mind sharing you repo ?

**Comment by tanguyantoine** [comment]
btw, I updated the library beacause lot of things have change since 2 weeks. Is the problem still present with the new version `0.4.0` ?

**Comment by natashache** [comment]
@tanguyantoine I just downloaded the lib from npm the day before yesterday. It says version 0.3.4. Just did a npm update. It didn't change. And [here's the component](https://github.com/natashache/soundwise/blob/master/src/containers/Player.js) where the library is used.

**Comment by tanguyantoine** [comment]
Can you try by forcing 0.4.0 in `package.json` ?

**Comment by tanguyantoine** [comment]
I tried to launched your app but not succeeded. extra step to do ?

**Comment by natashache** [comment]
@tanguyantoine What error message did you get when you tried to launch the app?

One reason can be because it's missing the firebase config file, which I gitignore-d. I can send it to you by email. What's your email address?

I tried force installing 0.4.0. I got an error:
![screenshot 2017-03-08 20 02 17](https://cloud.githubusercontent.com/assets/19754530/23731246/72ced562-043a-11e7-9c2c-005ae33e81c2.png)

**Comment by tanguyantoine** [comment]
can you retry to update again ? it looks  to be published

**Comment by natashache** [comment]
@tanguyantoine ok, will try it and let you know. Thanks.

**Comment by tanguyantoine** [comment]
did that worked ?

**Comment by natashache** [comment]
@tanguyantoine sorry I set this project aside for a while. Going to pick it up again this month. Will try it and let you know. Thank you so much!

**Comment by tanguyantoine** [comment]
I close this issue. feel free to ping here if you encounter the same problem
