### ISSUE TITLE
Item details not updated on Lock Screen.

### ISSUE THREAD

**Issue by deshiknaves** [tanguyantoine/react-native-music-control#52]
When a new item is set with `setPlayback` (as in if you press next from the lock screen), the image is updated, but the title or the time does not update.

This is on iOS on a Real device.

I'll see if I can find out why. Do you know about this at all?

**Comment by deshiknaves** [comment]
Looks like it's on the control center too. When it's in the background the new name and time not being updated. 

Weirdly enough - works fine when it is airplayed. Interesting bug :). I'll do some debugging tomorrow.

**Comment by deshiknaves** [comment]
This has to do with something completely different. Please ignore.

**Comment by Tejas-narola** [comment]
@deshiknaves  I have faced same issue duration time not updated when a user clicks to play/pause button. otherwise working fine.
would you please describe here what was an issue exactly and how to resolve it.
