### ISSUE TITLE
Album Artwork not working on iOS

### ISSUE THREAD

**Issue by SteffeyDev** [tanguyantoine/react-native-music-control#55]
Using local album artwork on iOS is causing the application to crash, because the javascript require() appears to be returning a number or something other than a string, so when the native module calls hasPrefix on it to check if it begins with "http://" the application crashes, saying that NSNumber does not have a function called hasPrefix.  I am not quite sure how require() works or if calling it below is correct:

`MusicControl.setNowPlaying({artwork: require('../Images/musicIcon.png')});`

But using just '../Images/musicIcon.png' (not wrapped in require), while not crashing, does not seem to work either (as expected).

**Comment by Guichaguri** [comment]
Local artworks using require are not supported on iOS yet. See #46 for details.
I think can specify the path as a string instead of using the require. I'm not an iOS dev though.
