### ISSUE TITLE
Android clicking notification item open new version of the app

### ISSUE THREAD

**Issue by deshiknaves** [tanguyantoine/react-native-music-control#58]
Having some weird behavior with the android version of the music control. Clicking on the tack in the notification brings up a second version of the app instead of the current version that is playing. 

![image](https://cloud.githubusercontent.com/assets/862834/24834596/e811ef7e-1d2d-11e7-9b6c-3d14af0bebf4.png)

1. Sample code (provide repo url or sample code)

2. Platform
   - [ x] Android
   
   
3. Device
  - [x ] Simulator - Genymotion, Nenxus 5 6.0

**Comment by deshiknaves** [comment]
My lack of understanding on how Android works

`android:launchMode="singleInstance"` takes care of it.

**Comment by xuananpham93** [comment]
@deshiknaves  Where can I put it, bro?
