### ISSUE TITLE
issue with your famous library

### ISSUE THREAD

**Issue by darbaoui** [tanguyantoine/react-native-music-control#60]
# Description
im using for playing audio this library [react-native-audio-streaming](https://github.com/tlenclos/react-native-audio-streaming)
but if i import only your library in my code in the top of javascript file
i have this error

![screenshot_1491752247](https://cloud.githubusercontent.com/assets/6907747/24838687/ec30d14e-1d44-11e7-86de-c13ff117c69f.png)

2. Platform ?
   
   - [ ] Android
   
   
3. Device
  - [ ] Simulator

**Comment by Guichaguri** [comment]
Did you follow the installation instructions?

**Comment by darbaoui** [comment]
yes 
![capture d ecran 2017-04-09 a 18 26 04](https://cloud.githubusercontent.com/assets/6907747/24839434/117ab782-1d52-11e7-97a8-b9c3203d1353.png)
ve

**Comment by tanguyantoine** [comment]
@darbaoui woudl you mind sharing your code ?

**Comment by darbaoui** [comment]
@tanguyantoine 
I resolved this issue by using this library [react-native-video](https://github.com/react-native-community/react-native-video), with your library
thanks @tanguyantoine
