### ISSUE TITLE
App crashing when killed from tabs

### ISSUE THREAD

**Issue by deshiknaves** [tanguyantoine/react-native-music-control#62]
# Description
When an app is killed from the from the background tabs, I get this issue.

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tanguyantoine.react.MusicControlNotification.hide()' on a null object reference
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3343)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 19:21:59.103  3394  3394 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

2. Platform ?
   - [ ] iOS
   - [x ] Android
   
   
3. Device
  - [x ] Simulator

**Comment by Guichaguri** [comment]
This was caused because the service is trying to clear the resources of the module, but they were cleared before because of low memory. I've added a fix that checks if it was already destroyed before trying to destroy.

**Comment by deshiknaves** [comment]
Awesome cheers.
