### ISSUE TITLE
Android: updatePlayback does not update title, artist and album.

### ISSUE THREAD

**Issue by valinaga** [tanguyantoine/react-native-music-control#63]
# Description
Title, artist, album, description not updated when using `MusicControl.updatePlayback`.

1. Sample code (provide repo url or sample code)
`MusicControl.updatePlayback({`
`    album: 'Capitolul 3',`
`    title: 'title',`
`    artist: 'artist',`
`    elapsedTime: 1,`
`    duration: 100,`
`});`

2. Platform ?
   - [- ] iOS
   - [X] Android
   
   
3. Device
  - [X] Simulator
  - [ ] Real device

**Comment by tanguyantoine** [comment]
you should use `setNowPlaying`, @Guichaguri can you confirm ?

**Comment by Guichaguri** [comment]
That's right. `setNowPlaying` is for information about the track, `updatePlayback` is for information about the player. It's all documented in the [readme](https://github.com/tanguyantoine/react-native-music-control/blob/master/README.md#use)

**Comment by valinaga** [comment]
@tanguyantoine, @Guichaguri Thanks!
