### ISSUE TITLE
Notification is minimized

### ISSUE THREAD

**Issue by dnish** [tanguyantoine/react-native-music-control#67]
Hey,
I'm having an issue with your great plugin. While playing music, the notification is minimized on lock screen. I have to click on it to show up the music controls. If I start f.e. Spotify, the music controls are visible the whole time and I'm able to control the playback without any further click on the lock screen. Any idea which setting is missing?

Platform ?
   - [ ] iOS
   - [x] Android
   
   
Device
  - [ ] Simulator
  - [x] Real device (OnePlus 3 - Android 7)

**Comment by DanNi0130** [comment]
I am having this issue as well, Android Version 5.0.1 on a Samsung Galaxy S4.

**Comment by gmverdon** [comment]
+1

**Comment by jankarres** [comment]
I had the same issue and I have solved it. I have the following control settings in my JS code:

```
        MusicControl.enableControl("play", true);
        MusicControl.enableControl("pause", true);
        MusicControl.enableControl("stop", false);
        MusicControl.enableControl("nextTrack", false);
        MusicControl.enableControl("previousTrack", false);

        // Seeking
        MusicControl.enableControl("seekForward", false); // iOS only
        MusicControl.enableControl("seekBackward", false); // iOS only
        MusicControl.enableControl("seek", true); // Android only
        MusicControl.enableControl("skipForward", true, { interval: 30 });
        MusicControl.enableControl("skipBackward", true, { interval: 30 });

        // Android Specific Options
        MusicControl.enableControl("setRating", false);
        MusicControl.enableControl("volume", true); // Only affected when remoteVolume is enabled
        MusicControl.enableControl("remoteVolume", false);
        MusicControl.enableControl("closeNotification", true, { when: "paused" });

        // iOS Specific Options
        MusicControl.enableControl("enableLanguageOption", false);
        MusicControl.enableControl("disableLanguageOption", false);
```

In the "hacked" solution you'll find the method setShowActionsInCompactView, which expects an index array of via builder.addAction() hooked actions. I am not a Java developer, so I cannot figure out a clean implantation of this feature. Actually @tanguyantoine could help out here? I think this would be a great feature for this package!

**Comment by tanguyantoine** [comment]
@Guichaguri is the android expert ;-)

**Comment by Guichaguri** [comment]
Yes, `setShowActionsInCompactView` is the proper way to do it. I can work on it when I have more time

**Comment by tanguyantoine** [comment]
please try `0.10.8`

**Comment by tanguyantoine** [comment]
closing (stale)
