### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by hongri** [tanguyantoine/react-native-music-control#8]
# when I archive my app, it failed because of RCTBridgeModule.h file not found.

# Tasks

- [ RCTBridgeModule.h file not found ]

**Comment by tanguyantoine** [comment]
Which platform? Did you follow all setup steps?

Generally this error arrive when you forget to include `libMusicControl.a`on ios

**Comment by hongri** [comment]
when I run in simulator is ok, but is not ok when I archive my app.
when I move the react native music control node module to react-navie and add the file to project, it's ok when I archive my app, but it's not ok in sumulator.

**Comment by tanguyantoine** [comment]
Do you have error stacktrace or other information ? Do you have this problem with other react native component?

**Comment by DClark5218** [comment]
+1 I am also getting this issue as well. I have included libMusicControl.a on ios.

Looking for some solutions.

**Comment by tanguyantoine** [comment]
I'm pretty it is because you forget to do link the binary during build phase. Can you send me your project?

**Comment by tanguyantoine** [comment]
Can you send a stack trace.

**Comment by DClark5218** [comment]
@tanguyantoine sure thing. When I try to build things this is what I get: 

<img width="1331" alt="musiccontrolmanager_m" src="https://cloud.githubusercontent.com/assets/4645553/16702057/a4eed65a-4531-11e6-8caf-dbc3d9873d86.png">

**Comment by DClark5218** [comment]
Is this correct?
<img width="1320" alt="screen shot 2016-07-08 at 5 33 16 pm" src="https://cloud.githubusercontent.com/assets/4645553/16702127/15d4b0a6-4532-11e6-9afa-c3947272192f.png">

**Comment by tanguyantoine** [comment]
Can you try to click on the plus button (into the **link binary with library** section) search for libMusicControl.a and add it

**Comment by DClark5218** [comment]
I don't think I can add that in that, as that is in the libMusicControl I added. When I click my project, you can see it has been added. Again, it works in debug fine, but not when I build for production.

<img width="896" alt="screen shot 2016-07-09 at 1 28 28 pm" src="https://cloud.githubusercontent.com/assets/4645553/16709252/0d9d9fe0-45d9-11e6-8eea-9d23b93379be.png">

Does this make sense? Is there anything I can do more to help?

**Comment by tanguyantoine** [comment]
https://github.com/facebook/react-native-fbsdk/issues/21 ?

**Comment by tanguyantoine** [comment]
???

**Comment by hongri** [comment]
still have this problem, when i add "$(SRCROOT)/../node_modules/react-native-music-control/React/**"

**Comment by tanguyantoine** [comment]
Sorry the ˋReact` at the end should be removed

**Comment by tanguyantoine** [comment]
Cause this folder does not exist

**Comment by hongri** [comment]
It's not work. "RCTBridgeModule.h file not found", when archive my app.

**Comment by tanguyantoine** [comment]
This file file is not from this package but from react-native. Seems that this issue is not related to react-native-music-control

**Comment by eds101** [comment]
react-native directories needed to be added to the xcodeproject's header search paths.

I submitted a PR which fixes this: https://github.com/tanguyantoine/react-native-music-control/pull/11

**Comment by marioot** [comment]
Still happening.
Re-adding those header search paths doesn't seem to solve the issue.
