### ISSUE TITLE
[Android 6.0 or 7.0] Crashing when load external image

### ISSUE THREAD

**Issue by theinvensi** [tanguyantoine/react-native-music-control#82]
# Description

1. Sample code (provide repo url or sample code)
![image](https://user-images.githubusercontent.com/4583856/29412254-eed39fac-8325-11e7-8be1-53d57f32b05e.png)

![image](https://user-images.githubusercontent.com/4583856/29412259-f5eb34da-8325-11e7-9dcc-15be011e5bba.png)

2. Platform ?
- [x] Android
   
3. Device
  - [x] Real device

This error appears on Play Store ARN Errors:

![image](https://user-images.githubusercontent.com/4583856/29412176-a4661d14-8325-11e7-8e27-5d9374575486.png)

Please somebody can help-me?

Thanks!

**Comment by Guichaguri** [comment]
Can you send the full error logs?

**Comment by tanguyantoine** [comment]
@theinvensi do you still have the issue ?

**Comment by tanguyantoine** [comment]
closing because of no response
