### ISSUE TITLE
putBitmap on a null object reference

### ISSUE THREAD

**Issue by anderslemke** [tanguyantoine/react-native-music-control#83]
# Description

I get the following error from Crashlytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.media.MediaMetadataCompat$Builder android.support.v4.media.MediaMetadataCompat$Builder.putBitmap(java.lang.String, android.graphics.Bitmap)' on a null object reference
       at com.tanguyantoine.react.MusicControlModule$1.run(MusicControlModule.java:224)
       at java.lang.Thread.run(Thread.java:833)
```

It has occurred on Android 5, 6 and 7 and a plethora of devices.

1. Sample code (provide repo url or sample code)

https://github.com/tanguyantoine/react-native-music-control/blob/196b3f89cf16a3718ddb0e29ec954a12faec87b1/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java#L224

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by Guichaguri** [comment]
Strange... The only way this can happen is when the module is destroyed, but when it destroys, it also stops the artwork thread

**Comment by Guichaguri** [comment]
Anyway, here is a quick fix

**Comment by anderslemke** [comment]
Thanks a lot @Guichaguri (You're here as well... 👍  )
