### ISSUE TITLE
Can't Load Image From Project

### ISSUE THREAD

**Issue by Jeremaiha** [tanguyantoine/react-native-music-control#87]
# Description
Hi, I'm trying to require a simple image from my project and I get a crash.
Can anyone help me ?

1. Sample code:
MusicControl.setNowPlaying({
      title: this.title,
      artwork: require('Images/someImage'), // URL or RN's image require()
      artist: "",
      album: "",
      genre: "",
      duration: parseInt(this.player.duration / 1000) // (Seconds)
    });

2. Platform ?
   - [X] iOS
   - [X] Android
   
   
3. Device
  - [x] Simulator
  - [X] Real device

**Comment by tanguyantoine** [comment]
logs ?

**Comment by Jeremaiha** [comment]
Basically now I'm using `file-url` module so it doesn't get crashed.
But I'm still receiving an empty image.
* What is the proper way to load the image's path: `Project/App/Images/myImage.png`

**Comment by tanguyantoine** [comment]
Can you make sure you followed these steps https://facebook.github.io/react-native/docs/images.html

**Comment by Jeremaiha** [comment]
@tanguyantoine 
Everything from your url seems ok, from what I saw in xcode, is it doesn't find the image.

**Comment by tanguyantoine** [comment]
If it does not show up in Xcode then this you should solve this issue before

**Comment by Jeremaiha** [comment]
@tanguyantoine 
It does show in Xcode, the problem is when trying to use `fileExistsAtPath`
When I disabled the if statement, and just gave the UIImageView to create the image from the path it worked.
Is it possible to remove that if-statement? not having it won't crash the app, the image will just be nil and nothing will show if the `path` is wrong.
Also, from what I read in stackoverflow they mentioned that the `fileExistsAtPath` is searching inside `udid` folders inside the application that's why it is a problematic way to check the existences of files.

Please have a look in the issue:
* https://stackoverflow.com/questions/9303875/fileexistsatpath-returning-no-for-files-that-exist

**Comment by tanguyantoine** [comment]
Which if statement are you talking about ?

**Comment by Jeremaiha** [comment]
1. Open Xcode
2. Go to file named `MusicControlManager.m` lines 249-252.
3. Code can be rewritten to just `image = [UIImage imageNamed:url];`

Give me your thoughts about it.

**Comment by tanguyantoine** [comment]
any chance you create a pull request for this ?

**Comment by Jeremaiha** [comment]
Yes I'll try.
Will let you know if something goes wrong

**Comment by Jeremaiha** [comment]
Apparently it says I need permissions to publish a pull request.
This is the change I suggest: 
![screen shot 2017-09-10 at 10 22 53](https://user-images.githubusercontent.com/7548074/30246997-1454f63c-9612-11e7-9752-0a784a984ff8.png)

**Comment by tanguyantoine** [comment]
In order to create a PR you need your own fork.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by Jeremaiha** [comment]
@tanguyantoine 
Hi again,
Please revert my latest PR, my fixes work on version 0.4.4, since I didn't update the repository I was working on, my changes were working.
Now that I've upgraded the package in the repository, it doesn't work, not sure at the moment to say why, I believe it has something to do with the 'artwork bug fixes' which were lately uploaded.
I will give a more in depth look later on, but for now I prefer that my PR will be revered so that users won't get any regressions.
Sorry for the inconvenience.

**Comment by tanguyantoine** [comment]
closed by #89

**Comment by tanguyantoine** [comment]
reverted
