### ISSUE TITLE
Different time when pause and re-playing audio

### ISSUE THREAD

**Issue by tiendn** [tanguyantoine/react-native-music-control#92]
# Play audio in background - iOS
  Current time is showed not right:
  * When **lock screen**, it begins from 0.
  * And then, when click **pause**, it returns the real time of audio 
  * But next, **play again** this is reset to 0. ( I didn't find any method for updating playing time ).

![issue](https://user-images.githubusercontent.com/15717476/30478490-6fea850c-9a3b-11e7-851d-d6927901f31a.gif)

1. Sample code (provide repo url or sample code)
```javascript
play() {
      if (this.whoosh.isLoaded()){
        this.whoosh.play((success) => {
          if (success) {
          } else {
            console.log('playback failed due to audio decoding errors');
          }
        });
    }
      const duration = this.whoosh.getDuration();
      MusicControl.setNowPlaying({
        title: this.props.bookData.titleVn,
        artwork: 'https://i.imgur.com/e1cpwdo.png',
        artist: this.props.bookData.chapters[this.currentChapter].title, //'Michael Jackson',
        // album: 'Thriller',
        // genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
        duration: duration,
        // description: 'Billie Jean is a song by American singer Michael Jackson. It is the second single from the singer\'s sixth solo album, Thriller (1982). It was written and composed by Jackson and produced by Jackson and Quincy Jones.',
        // date: '1983-01-02T00:00:00Z',
        rating: 84
      });
      this.setState({
        play: true
      });
    // }
  }
    

  pause(){
      this.whoosh.pause();
      this.whoosh.getCurrentTime((time) => {
        console.log(time);
        MusicControl.updatePlayback({
          state: MusicControl.STATE_PAUSED,
          elapsedTime: time
        });
      });
      // MusicControl.enableControl('play', false)
      // MusicControl.enableControl('pause', true)
      this.setState({
          play: false
      });
  }
```

2. Platform ?
   - [x] iOS
   - [ ] Android: Not tested
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by tanguyantoine** [comment]
Why do you set `elapsedTime`when you pause the song ? On the second play if you set `elapsedTime` does it work ?

**Comment by tiendn** [comment]
I set ```elapsedTime``` because I want to show the currentTime playing. 
And if didn't, the **currentTime** will be returned 0.
"On the second play if you set elapsedTime does it work ?" --> I don't know what you mean. 
Is that when play again, use method setNowPlaying() ?

**Comment by tiendn** [comment]
I set ```elapsedTime`` for saving the **currentTime** playing.
Ahha, thank you for your suggesting. I have defined wrong way when playing again.
Here is my code:
```javascript
replay() {
    console.log("Replay");
    this.whoosh.play();
    this.whoosh.getCurrentTime(time => {
      MusicControl.updatePlayback({
        state: MusicControl.STATE_PLAYING,
        elapsedTime: time
      });
    });
    this.setState({
      play: true
    });
  }
```

**Comment by tanguyantoine** [comment]
👍

**Comment by tiendn** [comment]
Ah, By the way. 
I have a question, about ```setNowPlaying()```, when set artwork from url online. 
But the request is **async**, it makes my ```artwork``` show late 2-second after **lock screen**. 
--> That's why my **current time** is less than **real current time**.
- So, can you update any options for that, such as load image before set ```artwork```?

**Comment by Guichaguri** [comment]
@tiendn You can download the image and setting from a path instead of an URL

**Comment by tiendn** [comment]
@Guichaguri , If I download, what happens with the dynamic image?
But I have another solution before I play audio, I have loaded the image before. So that the next time I call that image, it'll be rendered fastly. 
But I didn't know why 😅

**Comment by Guichaguri** [comment]
@tiendn It's OkHttp's caching.
