### ISSUE TITLE
Missing file extension for 'react-native-music-control'

### ISSUE THREAD

**Issue by Monte47** [tanguyantoine/react-native-music-control#94]
2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [ ] Real device

So this package is not working at all for me and my linter is giving me the error stated in the title. 

```
"dependencies": {
    "react-native-music-control": "^0.4.12",
  },

```

```
import PropTypes from 'prop-types';
import React, { Component } from 'react';
// import _ from 'lodash';
import {
  View,
  Image,
  StyleSheet,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Dimensions,
  Animated,
  StatusBar,
  Platform,
  ImageBackground,
  AppState,
} from 'react-native';

import MusicControl from 'react-native-music-control';
import { connect } from 'react-redux';

```

I cleaned and relinked everything to no avail.

**Comment by tanguyantoine** [comment]
if it is your linter then it is not linked to the package. Do you have a repo you can share ?

**Comment by Monte47** [comment]
I unfortunately can't share repo at this time since it is Private.

On device it actually works for the most part but now i'm having a separate issue with the lock screen not working when audio is paused. I will investigate further and make a separate issue if I can't figure it out.
