### ISSUE TITLE
Custom Now Playing theme

### ISSUE THREAD

**Issue by flarocca** [tanguyantoine/react-native-music-control#96]
Hey!! Firstly I wanted to say Thanks for your contribution!!! It is a great Lib!.
**This is more like a question rather than an issue**, I just wanted to know if there is a way to customise (Controls' position, icons, colors, etc) the theme of the NowPlaying control. Perhaps you guys can give me a clue on how to do it using ReactNative or Android Studio.

Thanks

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by Guichaguri** [comment]
You can replace the resource files for the icons. The color can be customized through the `color` option in `setNowPlaying`. The position of the buttons can not be changed unless you modify the code.

**Comment by MykolaSauliak** [comment]
> You can replace the resource files for the icons. The color can be customized through the `color` option in `setNowPlaying`. The position of the buttons can not be changed unless you modify the code.

What I need to modify to change custom theme ?
