### ISSUE TITLE
iOS 11 supported?

### ISSUE THREAD

**Issue by polp6880** [tanguyantoine/react-native-music-control#99]
Does this work on iOS 11 please? I've tried the example, can get it to work but control centre details are not updated. Thanks.

1. Sample code (provide repo url or sample code)
n/a

2. Platform ?
   - [x] iOS
   - [ ] Android
   
   
3. Device
  - [x] Simulator
  - [x] Real device

**Comment by natashache** [comment]
It stopped working after I installed iOS11. But it's working now after I restarted the phone.

**Comment by tanguyantoine** [comment]
@polp6880 did the restart fix the issue ?

**Comment by polp6880** [comment]
@tanguyantoine no, it did not fix for me.

**Comment by Stormcore** [comment]
Just update to XCode 9 Beta 2 and it will be fixed

**Comment by simonjking** [comment]
I am also experiencing problems in ios11. The playback bar does not update in the media player on the lock screen. It does update in control center (which I can only see by force touching the smaller audio widget).

**Comment by simonjking** [comment]
Never mind. Rebooting the phone did solve this for me.

**Comment by danielmilner** [comment]
I'm also experiencing this issue on iOS 11. Rebooting did not fix it. I even tried manually setting the elapsedTime, but it is not updating.

**Comment by marf** [comment]
I have the same problem, with iOS 11 the control center details (song metadata) are not updated.

**Comment by geroale** [comment]
Same problem on iOS 11. Please fix 😫 Rebooting is not working.

**Comment by ryanmeisters** [comment]
I had the same (or similar issue) and my problem was that I misread this part of the readme

> When using react-native-sound for audio playback, make sure that on iOS mixWithOthers is set to false in Sound.setCategory(value, mixWithOthers). MusicControl will not work on a real device when this is set to true.

and had `mixWithOthers ` set to true.

**Comment by marf** [comment]
Unfortunately we don't use `react-native-sound`, but we use `react-native-video`

**Comment by tanguyantoine** [comment]
@cinder92 are you using a real device?

**Comment by timmywil** [comment]
I think this is also fixed by b2b1acc293a3a477948176a4a9b7208660827d76

**Comment by tanguyantoine** [comment]
please try `0.10.8`
